version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --production=false
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf node_modules
      - rm -rf env
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
    - '/root/.npm/**/*'
