import { LangStringType } from '@/types/common';
import { CommunityBestNoticesTextType } from '@/types/textTypes';

export const CommunityBestNoticesTexts: LangStringType<CommunityBestNoticesTextType> = {
  ko: {
    title: 'BEST 소식',
    seeMore: '더보기',
    daily: '실시간',
    weekly: '주간',
    monthly: '월간',
    comment: '댓글순',
    recommend: '추천순',
  },
  en: {
    title: 'BEST',
    seeMore: 'See more',
    daily: 'daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    comment: 'Most commented',
    recommend: 'Most liked',
  },
  in: {
    title: 'Terbaik',
    seeMore: 'Lihat lebih banyak',
    daily: 'Saat ini',
    weekly: 'Mingguan',
    monthly: 'Bulanan',
    comment: 'Paling banyak dikomentari',
    recommend: 'Paling disukai',
  },
  ja: {
    title: 'ベスト',
    seeMore: '詳細を見る',
    daily: 'ライブ',
    weekly: '週間',
    monthly: '月間',
    comment: 'コメントが多い順',
    recommend: '推薦数多い順',
  },
  vi: {
    title: 'Tốt nhất',
    seeMore: 'Xem thêm',
    daily: 'Hiện nay',
    weekly: 'Hàng tuần',
    monthly: 'Hàng tháng',
    comment: 'Nhận xét nhiều nhất',
    recommend: 'Được đề xuất nhiều nhất',
  },
  'zh-CN': {
    title: '热门',
    seeMore: '查看详情',
    daily: '实时',
    weekly: '周榜',
    monthly: '月榜',
    comment: '评论最多',
    recommend: '赞最多',
  },
  'zh-TW': {
    title: '熱門',
    seeMore: '查看詳情',
    daily: '即時',
    weekly: '周榜',
    monthly: '月榜',
    comment: '評論最多',
    recommend: '讚最多',
  },
  es: {
    title: 'Best',
    seeMore: 'Ver más',
    daily: 'Actual',
    weekly: 'Semanal',
    monthly: 'Mensual',
    comment: 'Orden de muchos comentarios',
    recommend: 'orden de gran cantidad de recomendaciones',
  },
};
