import type { LangStringType } from '@/types/common';
import type { CommunityPostEditorTextType } from '@/types/textTypes';

export const communityPostEditorTexts: LangStringType<CommunityPostEditorTextType> = {
  ko: {
    pageTitle: '글쓰기',
    topic: '토픽',
    title: '제목',
    content: '내용',
    cancel: '취소',
    upload: '등록',
    edit: '수정',
    titlePlaceholder: '제목을 입력해 주세요',
    modal: {
      upload: '게시물을 등록하시겠어요?',
      cancelUpload: '글쓰기를 종료하시겠어요?',
      cancelUploadSub: '글쓰기 종료 시 작성 중인 글은 삭제 됩니다.',
      edit: '게시물을 수정하시겠어요?',
      cancelEdit: '수정을 취소하시겠어요?',
      enterTitle: '제목을 입력해 주세요',
      enterContent: '내용을 입력해 주세요',
      cancel: '취소',
      check: '확인',
    },
  },
  en: {
    pageTitle: 'Write',
    topic: 'Topic',
    title: 'Title',
    content: 'Contents',
    cancel: 'Cancel',
    upload: 'Upload',
    edit: 'Edit',
    titlePlaceholder: 'Please enter the title',
    modal: {
      upload: 'Do you want to upload a post?',
      cancelUpload: 'Do you want to leave writing a post?',
      cancelUploadSub: 'Your post will be deleted when you leave writing it',
      edit: 'Do you want to edit your post?',
      cancelEdit: 'Do you want to cancel editing your post?',
      enterTitle: 'Please enter the title',
      enterContent: 'Please enter text',
      cancel: 'Cancel',
      check: 'Check',
    },
  },
  es: {
    pageTitle: 'Escribir',
    topic: 'Tema',
    title: 'Título',
    content: 'Contenido',
    cancel: 'Cancelar',
    upload: 'Registrar',
    edit: 'Editar',
    titlePlaceholder: 'Ingresa el título',
    modal: {
      upload: '¿Te gustaría registrar la publicación?',
      cancelUpload: '¿Te gustaría dejar de escribir?',
      cancelUploadSub: 'Al dejar de escribir, el texto escrito se elimina.',
      edit: '¿Te gustaría editar la publicación?',
      cancelEdit: '¿Te gustaría cancelar la edición?',
      enterTitle: 'Ingresa el título',
      enterContent: 'Escribe el contenido',
      cancel: 'Cancelar',
      check: 'Confirmar',
    },
  },
  in: {
    pageTitle: 'Tulis',
    topic: 'Topik',
    title: 'Judul',
    content: 'Konten',
    cancel: 'Batal',
    upload: 'Unggah',
    edit: 'Edit',
    titlePlaceholder: 'Silakan masukkan judul',
    modal: {
      upload: 'Apakah Anda ingin mengunggah sebuah cerita?',
      cancelUpload: 'Apakah Anda ingin berhenti menulis cerita?',
      cancelUploadSub: 'Cerita Anda akan dihapus ketika Anda meninggalkan menulisnya',
      edit: 'Apakah Anda ingin mengedit cerita Anda?',
      cancelEdit: 'Apakah Anda ingin membatalkan mengedit cerita Anda?',
      enterTitle: 'Silakan masukkan judul',
      enterContent: 'masukkan garis',
      cancel: 'Batal',
      check: 'Memeriksa',
    },
  },
  ja: {
    pageTitle: '書き込み',
    topic: 'トピック',
    title: 'タイトル',
    content: '内容',
    cancel: 'キャンセル',
    upload: '登録',
    edit: '修正',
    titlePlaceholder: 'タイトルを入力してください',
    modal: {
      upload: '文を登録しますか？',
      cancelUpload: '書き込みを終了しますか？',
      cancelUploadSub: '終了時に作成されている文章は削除されます。',
      edit: '文を修正しますか？',
      cancelEdit: '修正を取り消しますか？',
      enterTitle: 'タイトルを入力してください',
      enterContent: '内容を入力してください',
      cancel: 'キャンセル',
      check: '確認',
    },
  },
  vi: {
    pageTitle: 'Viết',
    topic: 'Chủ đề',
    title: 'Đề mục',
    content: 'Nội dung',
    cancel: 'Hủy bỏ',
    upload: 'Tải lên',
    edit: 'Chỉnh sửa',
    titlePlaceholder: 'Vui lòng nhập tiêu đề',
    modal: {
      upload: 'Bạn có muốn tải lên một câu chuyện không?',
      cancelUpload: 'Bạn có muốn viết câu chuyện không?',
      cancelUploadSub: 'Câu chuyện của bạn sẽ bị xóa khi bạn viết nó',
      edit: 'Bạn có muốn chỉnh sửa câu chuyện của mình không?',
      cancelEdit: 'Bạn có muốn hủy chỉnh sửa câu chuyện của mình không?',
      enterTitle: 'Vui lòng nhập tiêu đề',
      enterContent: 'nhập các dòng',
      cancel: 'Hủy bỏ',
      check: 'Xác nhận',
    },
  },
  'zh-CN': {
    pageTitle: '发帖',
    topic: '话题',
    title: '标题',
    content: '内容',
    cancel: '取消',
    upload: '上传',
    edit: '修改',
    titlePlaceholder: '请输入标题',
    modal: {
      upload: '您要上传帖子吗？',
      cancelUpload: '您确定要退出写作吗？',
      cancelUploadSub: '编写结束时，正在编写的文章将被删除。',
      edit: '您确定要编辑帖子吗？',
      cancelEdit: '您确定要取消编辑吗？',
      enterTitle: '请输入标题',
      enterContent: '请填写内容',
      cancel: '取消',
      check: '确认',
    },
  },
  'zh-TW': {
    pageTitle: '發帖',
    topic: '話題',
    title: '標題',
    content: '內容',
    cancel: '取消',
    upload: '上傳',
    edit: '修改',
    titlePlaceholder: '請輸入標題',
    modal: {
      upload: '您要上傳帖子嗎？',
      cancelUpload: '您確定要退出寫作嗎？',
      cancelUploadSub: '編寫結束時，正在編寫的文章將被刪除。',
      edit: '您確定要編輯帖子嗎？',
      cancelEdit: '您確定要取消編輯嗎？',
      enterTitle: '請輸入標題',
      enterContent: '請填寫內容',
      cancel: '取消',
      check: '確認',
    },
  },
};
