import type { LangStringType } from '@/types/common';
import type { CommunityLayoutTextType } from '@/types/textTypes';

export const communityLayoutTexts: LangStringType<CommunityLayoutTextType> = {
  ko: {
    userCard: ['로그인을 해주세요', '내가 쓴 글', '로그아웃'],
    popularBoards: '인기 게시판',
    searchPlaceholder: '원하는 게시판을 찾아보세요.',
    close: '닫기',
    fanplusCommunity: '팬플러스 커뮤니티',
    bookmark: '즐겨찾기',
    asideMenus: ['전체글', '자유게시판'],
  },
  en: {
    popularBoards: 'Popular board',
    userCard: ['Sign In', 'My posts', 'Sign Out'],
    searchPlaceholder: 'Search for a board you may like.',
    close: 'Close',
    fanplusCommunity: 'Fanplus Community',
    bookmark: 'Bookmarks',
    asideMenus: ['All', 'Free Board'],
  },
  es: {
    popularBoards: 'Popular tablero',
    userCard: ['Inicio de sesión', 'El texto que escribí', 'Cierre de sesión'],
    searchPlaceholder: 'Encuentra el tablón de anuncios que deseas.',
    close: 'Cerrar',
    fanplusCommunity: 'Fanplus Comunidad',
    bookmark: 'Marca de libro',
    asideMenus: ['TODO', 'tablero libre'],
  },
  in: {
    popularBoards: 'Populer papan',
    userCard: ['Log Masuk', 'Cerita Saya', 'Log keluar'],
    searchPlaceholder: 'Cari papan yang mungkin Anda sukai.',
    close: 'Tutup',
    fanplusCommunity: 'Fanplus Komunitas',
    bookmark: 'Markah buku',
    asideMenus: ['SEMUA', 'Papan Gratis'],
  },
  ja: {
    popularBoards: '人気掲示板',
    userCard: ['ログオン', '私が書いた記事', 'ログアウト'],
    searchPlaceholder: '希望の掲示板を見つけてください。',
    close: '閉じる',
    fanplusCommunity: 'Fanplus コミュニティ',
    bookmark: 'ブックマーク',
    asideMenus: ['全て', 'フリーボード'],
  },
  vi: {
    popularBoards: 'Nổi tiếng board',
    userCard: ['Việc đăng nhập', 'Câu chuyện của tôi', 'Đăng xuất'],
    searchPlaceholder: 'Tìm kiếm một bảng bạn có thể thích.',
    close: 'Đóng',
    fanplusCommunity: 'Fanplus Tìm kiếm',
    bookmark: 'Đánh dấu',
    asideMenus: ['TẤT CẢ', 'Bảng miễn phí'],
  },
  'zh-CN': {
    popularBoards: '人气消息面板',
    userCard: ['登入', '我发的贴子', '退出登录'],
    searchPlaceholder: '找到您想要的消息面板',
    close: '关闭',
    fanplusCommunity: 'Fanplus 社区',
    bookmark: '关注',
    asideMenus: ['全部', '自由消息面'],
  },
  'zh-TW': {
    popularBoards: '人氣訊息面板',
    userCard: ['登入', '我發的貼子', '登出登入'],
    searchPlaceholder: '找到您想要的消息面板',
    close: '關閉',
    fanplusCommunity: 'Fanplus 社區',
    bookmark: '關注',
    asideMenus: ['全部', '自由消息面'],
  },
};
