import type { LangStringType } from '@/types/common';
import type { CommunityPostTextType } from '@/types/textTypes';

export const communityPostTexts: LangStringType<CommunityPostTextType> = {
  ko: {
    popular: '인기',
    post: '글',
    viewCount: '조회수',
    recommendCount: '추천수',
    recommend: '추천',
    edit: '수정',
    delete: '삭제',
    report: '신고하기',
    block: '차단하기',
    cancelButton: '취소',
    confirmButton: '확인',
    reportButton: '신고',
    commentRegisterPlaceholder: '댓글을 남겨주세요. (200자)',
    replyRegisterPlaceholder: '답글을 입력해 주세요. (200자)',
    askPostDelete: '게시글을 삭제하시겠어요?',
    askPostDeleteMsg: '게시글 삭제 시 글과 댓글이 모두 삭제됩니다',
    askCommentDelete: '댓글을 삭제하시겠어요?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: '게시물이 삭제되었습니다',
    commentDeleted: '댓글이 삭제되었습니다.',
    reported: '신고되었습니다.',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: '답글',
    writeReply: '답글쓰기',
    register: '등록',
    orderOldest: '등록순',
    orderNewest: '최신순',
    showMoreComments: '다음 댓글 더보기',
    deleted: '삭제된 댓글입니다.',
    alreadyDeleted: '이미 삭제된 댓글입니다.',
    alreadyReportedPost: '이미 신고한 게시글입니다.',
    alreadyReportedComment: '이미 신고한 댓글입니다.',
    reportReason: '사유 선택',
    reportPostOptions: {
      option1: '개인정보 노출',
      option2: '욕설/인신공격',
      option3: '음란/선정성',
      option4: '불법정보',
      option5: '권리침해',
      option6: '기타',
    },
    reportCommentOptions: {
      option1: '스팸',
      option2: '욕설 또는 악성 콘텐츠',
    },
    reportWarning: ['허위 신고의 경우 서비스 이용제한과 같은', '불이익을 받을 수 있습니다.'],
    daysAgo: '일 전',
    hoursAgo: '시간 전',
    minsAgo: '분 전',
    copyUrlButton: '주소복사',
    copyUrlMessage: '게시글 주소를 복사하였습니다.',
    postList: '목록',
    headerTitle: {
      all: '전체글',
      best: 'Best 인기글 (실시간)',
    },
  },
  en: {
    popular: 'Popular',
    post: 'Post',
    viewCount: 'View',
    recommendCount: 'Like',
    recommend: 'Like',
    edit: 'Edit',
    delete: 'Delete',
    report: 'Report',
    block: 'Block',
    cancelButton: 'Cancel',
    confirmButton: 'Check',
    reportButton: 'Report',
    commentRegisterPlaceholder: 'Leave a comment (max. 200 characters)',
    replyRegisterPlaceholder: 'Add a comment (max. 200 characters)',
    askPostDelete: 'Do you want to delete your post?',
    askPostDeleteMsg: 'If you delete your post, then your post and comments will also be deleted',
    askCommentDelete: 'Do you want to delete your comment?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: 'You’ve deleted your post.',
    commentDeleted: 'Comment deleted',
    reported: 'The issue has been successfully reported.',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: 'replies',
    writeReply: 'leave a reply',
    register: 'Upload',
    orderOldest: 'Earliest',
    orderNewest: 'Recent',
    showMoreComments: 'More comments',
    deleted: 'This comment has been deleted',
    alreadyDeleted: 'The comment has been deleted.',
    alreadyReportedPost: "You've already reported post",
    alreadyReportedComment: "You've already reported comment",
    reportReason: 'Select the reason.',
    reportPostOptions: {
      option1: 'Privacy violation',
      option2: 'Insult/Personal abuse',
      option3: 'Pornography/Sexual activity',
      option4: 'Illegal information',
      option5: 'An infringement report',
      option6: 'Other',
    },
    reportCommentOptions: {
      option1: 'Spam',
      option2: 'Insulting or inappropriate contents',
    },
    reportWarning: [
      'Reported content will be processed according to the operating policy and terms of use.',
      "If it is a false report, the reporter's use of FanPlus service may be restricted.",
    ],
    daysAgo: 'days ago',
    hoursAgo: 'hours ago',
    minsAgo: 'mins ago',
    copyUrlButton: 'Copy URL',
    copyUrlMessage: 'The URL of the post is copied.',
    postList: 'See List',
    headerTitle: {
      all: 'All',
      best: 'Most popular(live)',
    },
  },
  es: {
    popular: 'Popular',
    post: 'Texto',
    viewCount: 'Número de búsquedas',
    recommendCount: 'Gusta',
    recommend: 'Gusta',
    edit: 'Editar',
    delete: 'Eliminar',
    report: 'Reportar',
    block: 'Bloquear',
    cancelButton: 'Cancelar',
    confirmButton: 'Confirmar',
    reportButton: 'Reportar',
    commentRegisterPlaceholder: 'Dejar un comentario (200 caracteres)',
    replyRegisterPlaceholder: 'Ingresa un comentario (200 caracteres)',
    askPostDelete: '¿Te gustaría eliminar la publicación?',
    askPostDeleteMsg:
      'Al eliminar una publicación, tanto los textos como los comentarios son eliminados.',
    askCommentDelete: '¿Desea eliminar el comentario?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: 'La publicación ha sido eliminada',
    commentDeleted: 'El comentario ha sido eliminado.',
    reported: 'Ha sido reportado.',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: 'respuestas',
    writeReply: 'Escribe una respuesta',
    register: 'Registrar',
    orderOldest: 'Orden de registro',
    orderNewest: 'El más reciente',
    showMoreComments: 'leer más comentarios',
    deleted: 'Es un comentario eliminado.',
    alreadyDeleted: 'Es un comentario eliminado.',
    alreadyReportedPost: 'Es una publicación ya reportada.',
    alreadyReportedComment: 'Usted ha reportado una revisión',
    reportReason: 'Selecciona la razón de reporte.',
    reportPostOptions: {
      option1: 'Exposición de información personal',
      option2: 'Insultos/Ataque personal',
      option3: 'Acto obsceno/sexual',
      option4: 'Información ilegal',
      option5: 'Reporte de violación a los derechos',
      option6: 'Otros',
    },
    reportCommentOptions: {
      option1: 'Correo basura',
      option2: 'Insultos o contenido malicioso',
    },
    reportWarning: [
      'Se procederá el contenido denunciado según las políticas de operación y términos de uso. Si es una denuncia falsa,',
      'se podría restringir el uso del servicio de FanPlus por parte del denunciante.',
    ],
    daysAgo: 'Día(s) antes',
    hoursAgo: 'Hora(s) antes',
    minsAgo: 'Minuto(s) antes',
    copyUrlButton: 'Copiar URL',
    copyUrlMessage: 'Se copia la URL de la publicación.',
    postList: 'Lista',
    headerTitle: {
      all: 'TODO',
      best: 'Más popular (actual)',
    },
  },
  in: {
    popular: 'Popular',
    post: 'Post',
    viewCount: 'Lihat',
    recommendCount: 'Seperti',
    recommend: 'Seperti',
    edit: 'Edit',
    delete: 'Hapus',
    report: 'Laporkan',
    block: 'Blok',
    cancelButton: 'Batal',
    confirmButton: 'Memeriksa',
    reportButton: 'Laporkan',
    commentRegisterPlaceholder: 'Tinggalkan komentar (maksimal 200 karakter)',
    replyRegisterPlaceholder: 'Tulis komentar (maksimal 200 karakter)',
    askPostDelete: 'Apakah Anda ingin menghapus cerita Anda?',
    askPostDeleteMsg:
      'Jika Anda menghapus cerita Anda, maka cerita dan komentar Anda juga akan dihapus',
    askCommentDelete: 'Anda mau menghapus komentar?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: 'Anda telah menghapus kisah Anda',
    commentDeleted: 'Komentar sudah dihapus.',
    reported: 'Masalah ini telah berhasil dilaporkan.',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: 'balasan',
    writeReply: 'Menulis balasan',
    register: 'Unggah',
    orderOldest: 'Paling awal',
    orderNewest: 'Baru',
    showMoreComments: 'lebih banyak komentar',
    deleted: 'Komentar telah dihapus.',
    alreadyDeleted: 'Komentar sudah dihapus',
    alreadyReportedPost: 'Anda sudah melaporkan pos',
    alreadyReportedComment: 'Anda sudah melaporkan komentar',
    reportReason: 'Pilih alasannya.',
    reportPostOptions: {
      option1: 'Pengungkapan informasi pribadi',
      option2: 'Penghinaan / penyalahgunaan Pribadi',
      option3: 'Pornografi / Sensasi seksual',
      option4: 'Informasi ilegal',
      option5: 'Laporan pelanggaran',
      option6: 'Lainnya',
    },
    reportCommentOptions: {
      option1: 'Spam',
      option2: 'Konten yang menghina atau tidak pantas',
    },
    reportWarning: [
      'Konten yang dilaporkan akan diproses sesuai dengan kebijakan pengoperasian dan persyaratan penggunaan. Jika ini adalah laporan palsu,',
      'penggunaan layanan FanPlus oleh pelapor dapat dibatasi.',
    ],
    daysAgo: 'hari sebelumnya',
    hoursAgo: 'jam sebelumnya',
    minsAgo: 'menit sebelumnya',
    copyUrlButton: 'Salin URL',
    copyUrlMessage: 'URL postingan disalin.',
    postList: 'Daftar',
    headerTitle: {
      all: 'SEMUA',
      best: 'Paling populer(saat ini)',
    },
  },
  ja: {
    popular: '人気',
    post: '文',
    viewCount: 'ヒット',
    recommendCount: 'おすすめ',
    recommend: 'おすすめ',
    edit: '修正',
    delete: '削除',
    report: '申告する',
    block: 'ブロック',
    cancelButton: 'キャンセル',
    confirmButton: '確認',
    reportButton: '申告する',
    commentRegisterPlaceholder: 'コメントを残す（最大200文字)',
    replyRegisterPlaceholder: 'コメントを入力してください。（最大200文字)',
    askPostDelete: '文を削除しますか？',
    askPostDeleteMsg: '文削除時の内容とコメントがすべて削除されます。',
    askCommentDelete: 'コメントを削除しますか？',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: '文が削除されました。',
    commentDeleted: 'コメントが削除されました。',
    reported: '問題が正常に報告されています。',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: '返信',
    writeReply: '返事を書く',
    register: '登録',
    orderOldest: '最も早い',
    orderNewest: '最近',
    showMoreComments: 'コメントをもっと読む',
    deleted: '削除されたコメントです。',
    alreadyDeleted: '既に削除されたコメントです。',
    alreadyReportedPost: '既に申告したスレッドです。',
    alreadyReportedComment: 'コメントを報告しました。',
    reportReason: '理由を選択してください。',
    reportPostOptions: {
      option1: '個人情報の露出',
      option2: '悪口/人身攻撃',
      option3: 'エッチ/扇情性',
      option4: '不法情報',
      option5: '権利侵害申告',
      option6: 'その他',
    },
    reportCommentOptions: {
      option1: 'スパム',
      option2: '悪口または悪意のあるコンテンツ',
    },
    reportWarning: [
      '報告されたコンテンツは、運用ポリシーと利用規約に従って処理されます。虚偽の報告である場合、',
      'If it is a false report, 記者によるFanPlusサービスの使用が制限される場合があります。',
    ],
    daysAgo: '日 前',
    hoursAgo: '時間 前',
    minsAgo: '分 前',
    copyUrlButton: 'URLコピー',
    copyUrlMessage: '投稿のURLがコピーされます。',
    postList: 'リスト',
    headerTitle: {
      all: '全て',
      best: '最も人気（ライブ）',
    },
  },
  vi: {
    popular: 'Nổi tiếng',
    post: 'Câu chuyện',
    viewCount: 'Xem',
    recommendCount: 'Giống như',
    recommend: 'Giống như',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    report: 'Khai báo',
    block: 'Khối',
    cancelButton: 'Hủy bỏ',
    confirmButton: 'Xác nhận',
    reportButton: 'Khai báo',
    commentRegisterPlaceholder: 'Để lại một bình luận (tối đa 200 ký tự)',
    replyRegisterPlaceholder: 'Vui lòng nhập bình luận (tối đa 200 ký tự)',
    askPostDelete: 'Bạn có muốn xóa câu chuyện của mình không?',
    askPostDeleteMsg: 'Nếu bạn xóa câu chuyện, câu chuyện và nhận xét của bạn cũng sẽ bị xóa',
    askCommentDelete: 'Bạn muốn xóa bình luận?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: 'Bạn đã xóa câu chuyện của mình',
    commentDeleted: 'Bình luận đã được xóa',
    reported: 'Vấn đề này đã được báo cáo thành công.',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: 'câu trả lời',
    writeReply: 'Viết thư trả lời',
    register: 'Tải lên',
    orderOldest: 'Sớm nhất',
    orderNewest: 'Gần đây',
    showMoreComments: 'Xem thêm bình luận',
    deleted: 'Bình luận đã bị xóa',
    alreadyDeleted: 'Đã xóa nhận xét',
    alreadyReportedPost: 'Bạn đã báo cáo bài đăng',
    alreadyReportedComment: 'Đây là bình luận đã báo cáo rồi.',
    reportReason: 'Chọn lý do.',
    reportPostOptions: {
      option1: 'Tiết lộ thông tin cá nhân',
      option2: 'Xúc phạm / lạm dụng cá nhân',
      option3: 'Nội dung khiêu dâm / Cảm giác tình dục',
      option4: 'Thông tin bất hợp pháp',
      option5: 'Báo cáo vi phạm',
      option6: 'Khác',
    },
    reportCommentOptions: {
      option1: 'Spam',
      option2: 'Nội dung xúc phạm hoặc không phù hợp',
    },
    reportWarning: [
      'Nội dung được báo cáo sẽ được xử lý theo chính sách hoạt động và điều khoản sử dụng. Nếu đó là một báo cáo sai sự thật,',
      'việc sử dụng dịch vụ FanPlus của phóng viên có thể bị hạn chế. ',
    ],
    daysAgo: 'Ngày trước',
    hoursAgo: 'Giờ trước',
    minsAgo: 'Phút trước',
    copyUrlButton: 'Sao chép URL',
    copyUrlMessage: 'URL của bài viết được sao chép.',
    postList: 'Danh sách',
    headerTitle: {
      all: 'TẤT CẢ',
      best: 'Phổ biến nhất (hiện tại)',
    },
  },
  'zh-CN': {
    popular: '人气',
    post: '帖子',
    viewCount: '阅读数',
    recommendCount: '推荐',
    recommend: '推荐',
    edit: '修改',
    delete: '删除',
    report: '举报',
    block: '屏蔽',
    cancelButton: '取消',
    confirmButton: '确认',
    reportButton: '举报',
    commentRegisterPlaceholder: '请发表评论。（200字）',
    replyRegisterPlaceholder: '请输入评论。（200字）',
    askPostDelete: '您要删除该帖子吗？',
    askPostDeleteMsg: '删除帖子时，帖子内容和评论都将被删除。',
    askCommentDelete: '确认删除评论吗?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: '帖子已删除',
    commentDeleted: '评论已删除',
    reported: '已经举报。',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: '回复',
    writeReply: '写回复',
    register: '上传',
    orderOldest: '登录顺序',
    orderNewest: '最新顺序',
    showMoreComments: '阅读更多评论',
    deleted: '已被删除的评论',
    alreadyDeleted: '已被删除的评论。',
    alreadyReportedPost: '这篇文章已被举报。',
    alreadyReportedComment: '您已经报告了一个评论',
    reportReason: '请选择举报原因。',
    reportPostOptions: {
      option1: '个人信息曝光',
      option2: '亵渎/人身攻击',
      option3: '淫秽/煽情性',
      option4: '非法信息',
      option5: '侵权投诉',
      option6: '其他',
    },
    reportCommentOptions: {
      option1: '垃圾信息',
      option2: '淫秽或恶意内容',
    },
    reportWarning: [
      '举报内容将根据运营政策和使用条款进行处理。',
      '如果是虚假举报，则可能会限制举报人对服务的使用。',
    ],
    daysAgo: '日 前',
    hoursAgo: '小时 前',
    minsAgo: '分钟 前',
    copyUrlButton: '复制URL',
    copyUrlMessage: '帖子的 URL 已复制。',
    postList: '列表',
    headerTitle: {
      all: '全部',
      best: '热门（实时）',
    },
  },
  'zh-TW': {
    popular: '人氣',
    post: '帖子',
    viewCount: '閱讀數',
    recommendCount: '推薦',
    recommend: '推薦',
    edit: '修改',
    delete: '刪除',
    report: '舉報',
    block: '屏蔽',
    cancelButton: '取消',
    confirmButton: '確認',
    reportButton: '舉報',
    commentRegisterPlaceholder: '請發表評論。（200字）',
    replyRegisterPlaceholder: '請輸入評論。（200字）',
    askPostDelete: '您要刪除該帖子嗎？',
    askPostDeleteMsg: '刪除帖子時，帖子內容和評論都將被刪除。',
    askCommentDelete: '確認刪除評論嗎?',
    askBlockUser: [
      '이 회원의 게시글/댓글을',
      '차단하시겠습니까?',
      '이 회원이 쓴 글과 댓글이 보이지 않습니다.',
    ],
    postDeleted: '帖子已刪除',
    commentDeleted: '評論已刪除',
    reported: '已經舉報。',
    blockedUser: '회원을 차단하였습니다.',
    alreadyBlockUser: '이미 차단된 회원입니다.',
    reply: '回覆',
    writeReply: '寫回覆',
    register: '上傳',
    orderOldest: '登錄順序',
    orderNewest: '最新順序',
    showMoreComments: '閱讀更多評論',
    deleted: '已被刪除的評論',
    alreadyDeleted: '已被刪除的評論。',
    alreadyReportedPost: '這篇文章已被舉報。',
    alreadyReportedComment: '您已經報告了一個評論',
    reportReason: '請選擇舉報原因。',
    reportPostOptions: {
      option1: '個人信息曝光',
      option2: '褻瀆/人身攻擊',
      option3: '淫穢/煽情性',
      option4: '非法信息',
      option5: '侵權投訴',
      option6: '其他',
    },
    reportCommentOptions: {
      option1: '垃圾信息',
      option2: '淫穢或惡意內容',
    },
    reportWarning: [
      '舉報內容將根據運營政策和使用條款進行處理。',
      '如果是虛假舉報，則可能會限制舉報人對服務的使用。',
    ],
    daysAgo: '日 前',
    hoursAgo: '小時 前',
    minsAgo: '分鐘 前',
    copyUrlButton: '複製URL',
    copyUrlMessage: '貼文的 URL 已複製。',
    postList: '清單',
    headerTitle: {
      all: '全部',
      best: '熱門（即時）',
    },
  },
};
