import { LangStringType } from '@/types/common';
import { CommunityBestNoticesTextType } from '@/types/textTypes';

export const CommunityBestNoticesTexts: LangStringType<CommunityBestNoticesTextType> = {
  ko: {
    title: '팬플러스 BEST 이야기',
    seeMore: '더보기',
    daily: '실시간',
    weekly: '주간',
    monthly: '월간',
    comment: '댓글순',
    recommend: '추천순',
  },
  en: {
    title: 'Top Ranked',
    seeMore: 'See more',
    daily: 'daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    comment: 'Most commented',
    recommend: 'Most liked',
  },
  in: {
    title: 'Peringkat teratas',
    seeMore: 'Lihat lebih banyak',
    daily: 'Saat ini',
    weekly: 'Mingguan',
    monthly: 'Bulanan',
    comment: 'Melalui komentar',
    recommend: 'Paling disukai',
  },
  ja: {
    title: '上位ランク',
    seeMore: '詳細を見る',
    daily: 'ライブ',
    weekly: '週間',
    monthly: '月間',
    comment: 'コメント順',
    recommend: '推奨順',
  },
  vi: {
    title: 'Đứng đầu',
    seeMore: 'Xem thêm',
    daily: 'Hiện nay',
    weekly: 'Hàng tuần',
    monthly: 'Hàng tháng',
    comment: 'Bằng bình luận',
    recommend: 'Khuyến khích',
  },
  'zh-CN': {
    title: 'FanPlus 热门',
    seeMore: '查看详情',
    daily: '实时',
    weekly: '周榜',
    monthly: '月榜',
    comment: '评论最多',
    recommend: '赞最多',
  },
  'zh-TW': {
    title: 'FanPlus 熱門',
    seeMore: '查看詳情',
    daily: '即時',
    weekly: '周榜',
    monthly: '月榜',
    comment: '評論最多',
    recommend: '讚最多',
  },
  es: {
    title: 'Mejor clasificado',
    seeMore: 'Ver más',
    daily: 'Actual',
    weekly: 'Semanal',
    monthly: 'Mensual',
    comment: 'Por comentario',
    recommend: 'Recomendado',
  },
};
