import type { FAQPageTextType } from '@/types/textTypes';
import type { LangStringType } from '@/types/common';

export const faqPageTexts: LangStringType<FAQPageTextType> = {
  ko: {
    header: '무엇을 도와드릴까요?',
    navBar: {
      all: '전체',
      vote: '투표',
      photos: '사진',
      fanfic: '팬픽',
      accounts: '계정',
    },
    q1: '팬플러스는 어떤 서비스인가요?',
    a1: '팬플러스는 최애가 같은 팬들을 대상으로 다양한 콘텐츠와 소통 기능을 제공하는 종합 덕질 앱이에요. 유일하게 유료 결제 없는 아이돌 생일/기념일 투표를 진행하고 있답니다. 팬플러스에서 덕질에 즐거움을 더해보세요.',
    q2: '투표는 어떻게 참여할 수 있나요?',
    a2: '유료 결제 없이 앱 내 출석체크와 친구 초대를 통해 캐시를 획득할 수 있어요. 획득한 캐시를 투표권으로 교환하여 내 최애에게 투표해보세요.',
    q3: '광고는 언제/어떻게 진행되나요?',
    a3: '매달 생일/기념일 투표와 주제별 투표가 진행되고 있어요. 투표 결과에 따라 팬들이 응모한 시안 중 가장 많은 지지를 받은 시안으로 광고가 이루어져요.',
    q4: '투표는 언제부터 준비하나요?',
    a4: '생일에 해당하는 달로부터 약 2개월 전에 투표가 시작돼요. 주제별 투표는 트위터 공지를 통해 후보 제보를 받고 있으니, 공지를 참고해주세요.',
    twitter: '팬플러스 트위터 바로가기',
    q5: '사진 기능은 어떻게 사용할 수 있나요?',
    a5: '나와 최애가 같은 팬들이 직접 올린 사진을 구경하고 다운 받아보세요. 마음에 드는 사진이 있다면 바로 배경화면으로 설정할 수도 있어요.',
    q6: '비주얼 팬픽이 뭔가요?',
    a6: '기존 줄글 형식의 팬픽에서 벗어나 배경/인물/대사로 구성된 장면(씬)으로 이야기가 진행되는 형식이에요.',
    q7: '팬픽 출금 기능은 어떻게 사용하는 건가요?',
    a7: '독자에게 응원을 받으면 팝콘 아이템이 적립돼요. 팝콘을 모아 출금 신청을 할 수 있어요. 단, 현재는 번호 인증을 완료한 한국 유저만 이용이 가능해요.',
    q8: '팬플러스 탈퇴 후 재가입은 언제할 수 있나요?',
    a8: '탈퇴 후 재가입은 바로 가능해요. 다만, 어뷰징 방지를 위해 탈퇴된 계정과 동일한 닉네임/계정 주소/인증된 번호로는 탈퇴일로부터 90일간 가입이 제한됩니다.',
    q9: '탈퇴 후 같은 번호로 다시 인증하는 건 언제부터 가능한가요?',
    a9: '탈퇴한 계정에 인증되어 있는 번호는 탈퇴일로부터 90일이 지난 이후에 다시 번호 인증에 사용할 수 있어요.',
  },
  en: {
    header: 'We are here to help.',
    navBar: {
      all: 'All',
      vote: 'Vote',
      photos: 'Photos',
      fanfic: 'Fanfic',
      accounts: 'Accounts',
    },
    q1: 'What is FanPlus?',
    a1: 'FanPlus is a comprehensive app for worldwide Kpop fans that provides various contents and communication features. It is the only vote app without any payment. Have more fun for your fan life on Fanplus.',
    q2: 'How can I vote on FanPlus?',
    a2: 'You can get cash through daily attendance or inviting friends or participate in mission on offer-walls. Exchange your earned cash for voting tickets and vote for your favorite star.',
    q3: 'How will the reward ADs for vote winners be given?',
    a3: 'FanPlus holds birthday/debut anniversary votes and special themed votes every month. The winner will get a reward ADs depending on the voting result, and the AD content will be made and chosen by fans. AD locations may change every month.',
    q4: 'From when does the vote start and how do we know it?',
    a4: "A birthday/debut anniversary vote starts about two months before the month of your bias' birthday/debut anniversary. Also, we nominate candidates from requests on FanPlus Twitter for a special themed vote. Please refer to our notice tweets related to the vote on FanPlus Twitter.",
    twitter: 'Go to Fanplus Twitter',
    q5: "How can I use 'Photo' feature?",
    a5: 'Check & download photos posted by fans who are stan for the same bias as you. You can set your favorite photo as wallpaper on your mobile too.',
    q6: "What is 'Visual Fanfic'?",
    a6: 'Visual fanfic shows not only texts but also chat-style slides with background photos, characters, and scripts.',
    q7: '',
    a7: '',
    q8: 'Is it possible to re-register on FanPlus after deactivating my account?',
    a8: 'You can re-register on FanPlus anytime. However, you can use the same email address/nickname/mobile number 90 days after deactivation.',
    q9: 'When can I use the same mobile number from my old account to verify?',
    a9: 'You can use the mobile number which has been verified with the deactivated account 90 days after deactivation.',
  },
  es: {
    header: 'We are here to help.',
    navBar: {
      all: 'All',
      vote: 'Vote',
      photos: 'Photos',
      fanfic: 'Fanfic',
      accounts: 'Accounts',
    },
    q1: 'What is FanPlus?',
    a1: 'FanPlus is a comprehensive app for worldwide Kpop fans that provides various contents and communication features. It is the only vote app without any payment. Have more fun for your fan life on Fanplus.',
    q2: 'How can I vote on FanPlus?',
    a2: 'You can get cash through daily attendance or inviting friends or participate in mission on offer-walls. Exchange your earned cash for voting tickets and vote for your favorite star.',
    q3: 'How will the reward ADs for vote winners be given?',
    a3: 'FanPlus holds birthday/debut anniversary votes and special themed votes every month. The winner will get a reward ADs depending on the voting result, and the AD content will be made and chosen by fans. AD locations may change every month.',
    q4: 'From when does the vote start and how do we know it?',
    a4: "A birthday/debut anniversary vote starts about two months before the month of your bias' birthday/debut anniversary. Also, we nominate candidates from requests on FanPlus Twitter for a special themed vote. Please refer to our notice tweets related to the vote on FanPlus Twitter.",
    twitter: 'Go to Fanplus Twitter',
    q5: "How can I use 'Photo' feature?",
    a5: 'Check & download photos posted by fans who are stan for the same bias as you. You can set your favorite photo as wallpaper on your mobile too.',
    q6: "What is 'Visual Fanfic'?",
    a6: 'Visual fanfic shows not only texts but also chat-style slides with background photos, characters, and scripts.',
    q7: '',
    a7: '',
    q8: 'Is it possible to re-register on FanPlus after deactivating my account?',
    a8: 'You can re-register on FanPlus anytime. However, you can use the same email address/nickname/mobile number 90 days after deactivation.',
    q9: 'When can I use the same mobile number from my old account to verify?',
    a9: 'You can use the mobile number which has been verified with the deactivated account 90 days after deactivation.',
  },
  in: {
    header: 'We are here to help.',
    navBar: {
      all: 'All',
      vote: 'Vote',
      photos: 'Photos',
      fanfic: 'Fanfic',
      accounts: 'Accounts',
    },
    q1: 'What is FanPlus?',
    a1: 'FanPlus is a comprehensive app for worldwide Kpop fans that provides various contents and communication features. It is the only vote app without any payment. Have more fun for your fan life on Fanplus.',
    q2: 'How can I vote on FanPlus?',
    a2: 'You can get cash through daily attendance or inviting friends or participate in mission on offer-walls. Exchange your earned cash for voting tickets and vote for your favorite star.',
    q3: 'How will the reward ADs for vote winners be given?',
    a3: 'FanPlus holds birthday/debut anniversary votes and special themed votes every month. The winner will get a reward ADs depending on the voting result, and the AD content will be made and chosen by fans. AD locations may change every month.',
    q4: 'From when does the vote start and how do we know it?',
    a4: "A birthday/debut anniversary vote starts about two months before the month of your bias' birthday/debut anniversary. Also, we nominate candidates from requests on FanPlus Twitter for a special themed vote. Please refer to our notice tweets related to the vote on FanPlus Twitter.",
    twitter: 'Go to Fanplus Twitter',
    q5: "How can I use 'Photo' feature?",
    a5: 'Check & download photos posted by fans who are stan for the same bias as you. You can set your favorite photo as wallpaper on your mobile too.',
    q6: "What is 'Visual Fanfic'?",
    a6: 'Visual fanfic shows not only texts but also chat-style slides with background photos, characters, and scripts.',
    q7: '',
    a7: '',
    q8: 'Is it possible to re-register on FanPlus after deactivating my account?',
    a8: 'You can re-register on FanPlus anytime. However, you can use the same email address/nickname/mobile number 90 days after deactivation.',
    q9: 'When can I use the same mobile number from my old account to verify?',
    a9: 'You can use the mobile number which has been verified with the deactivated account 90 days after deactivation.',
  },
  ja: {
    header: 'We are here to help.',
    navBar: {
      all: 'All',
      vote: 'Vote',
      photos: 'Photos',
      fanfic: 'Fanfic',
      accounts: 'Accounts',
    },
    q1: 'What is FanPlus?',
    a1: 'FanPlus is a comprehensive app for worldwide Kpop fans that provides various contents and communication features. It is the only vote app without any payment. Have more fun for your fan life on Fanplus.',
    q2: 'How can I vote on FanPlus?',
    a2: 'You can get cash through daily attendance or inviting friends or participate in mission on offer-walls. Exchange your earned cash for voting tickets and vote for your favorite star.',
    q3: 'How will the reward ADs for vote winners be given?',
    a3: 'FanPlus holds birthday/debut anniversary votes and special themed votes every month. The winner will get a reward ADs depending on the voting result, and the AD content will be made and chosen by fans. AD locations may change every month.',
    q4: 'From when does the vote start and how do we know it?',
    a4: "A birthday/debut anniversary vote starts about two months before the month of your bias' birthday/debut anniversary. Also, we nominate candidates from requests on FanPlus Twitter for a special themed vote. Please refer to our notice tweets related to the vote on FanPlus Twitter.",
    twitter: 'Go to Fanplus Twitter',
    q5: "How can I use 'Photo' feature?",
    a5: 'Check & download photos posted by fans who are stan for the same bias as you. You can set your favorite photo as wallpaper on your mobile too.',
    q6: "What is 'Visual Fanfic'?",
    a6: 'Visual fanfic shows not only texts but also chat-style slides with background photos, characters, and scripts.',
    q7: '',
    a7: '',
    q8: 'Is it possible to re-register on FanPlus after deactivating my account?',
    a8: 'You can re-register on FanPlus anytime. However, you can use the same email address/nickname/mobile number 90 days after deactivation.',
    q9: 'When can I use the same mobile number from my old account to verify?',
    a9: 'You can use the mobile number which has been verified with the deactivated account 90 days after deactivation.',
  },
  vi: {
    header: 'We are here to help.',
    navBar: {
      all: 'All',
      vote: 'Vote',
      photos: 'Photos',
      fanfic: 'Fanfic',
      accounts: 'Accounts',
    },
    q1: 'What is FanPlus?',
    a1: 'FanPlus is a comprehensive app for worldwide Kpop fans that provides various contents and communication features. It is the only vote app without any payment. Have more fun for your fan life on Fanplus.',
    q2: 'How can I vote on FanPlus?',
    a2: 'You can get cash through daily attendance or inviting friends or participate in mission on offer-walls. Exchange your earned cash for voting tickets and vote for your favorite star.',
    q3: 'How will the reward ADs for vote winners be given?',
    a3: 'FanPlus holds birthday/debut anniversary votes and special themed votes every month. The winner will get a reward ADs depending on the voting result, and the AD content will be made and chosen by fans. AD locations may change every month.',
    q4: 'From when does the vote start and how do we know it?',
    a4: "A birthday/debut anniversary vote starts about two months before the month of your bias' birthday/debut anniversary. Also, we nominate candidates from requests on FanPlus Twitter for a special themed vote. Please refer to our notice tweets related to the vote on FanPlus Twitter.",
    twitter: 'Go to Fanplus Twitter',
    q5: "How can I use 'Photo' feature?",
    a5: 'Check & download photos posted by fans who are stan for the same bias as you. You can set your favorite photo as wallpaper on your mobile too.',
    q6: "What is 'Visual Fanfic'?",
    a6: 'Visual fanfic shows not only texts but also chat-style slides with background photos, characters, and scripts.',
    q7: '',
    a7: '',
    q8: 'Is it possible to re-register on FanPlus after deactivating my account?',
    a8: 'You can re-register on FanPlus anytime. However, you can use the same email address/nickname/mobile number 90 days after deactivation.',
    q9: 'When can I use the same mobile number from my old account to verify?',
    a9: 'You can use the mobile number which has been verified with the deactivated account 90 days after deactivation.',
  },
  'zh-CN': {
    header: '您需要什么帮助？',
    navBar: {
      all: '全部',
      vote: '投票',
      photos: '图片',
      fanfic: '王道文',
      accounts: '账户',
    },
    q1: 'Fanplus提供怎样的服务?',
    a1: 'Fanplus是以最爱偶像相同的粉丝为对象, 提供多样化信息和通讯功能的全面追星的应用程序。 唯一在生日/纪念日可以免费为偶像投票。 在Fanplus中体验追星的快乐。',
    q2: '如何参加投票？',
    a2: '您可以通过应用内出勤签到和邀请好友获得金币, 且无需付费。 将您获得的金币兑换为投票券后, 为您最喜欢的偶像投票。',
    q3: '广告何时/如何投放？',
    a3: '每月以生日/周年纪念日投票和按主题投票进行。 根据投票结果, 广告将以在粉丝提交的素材中, 获得票数最多的素材进行投放。',
    q4: '什么时候开始准备投票？',
    a4: '投票于相应生日的2个月前开始进行。 主题投票通过Twitter公布候选人, 请参阅公告。 转到Fanplus Twitter',
    twitter: '推特(Twitter)',
    q5: '如何使用图片功能？',
    a5: '查看并下载和自己的最爱偶像相同的粉丝上传发布的图片。 如果有喜欢的图片，可以直接设置成墙纸。',
    q6: '什么是视觉王道文？',
    a6: '与现有的线型幻想不同, 它是一种以背景/角色/台词组成的场面（场景）作为故事情节的方式进行。',
    q7: '',
    a7: '',
    q8: '注销Fanplus后, 什么时候可以重新注册?',
    a8: '注销后可以立即重新注册。 只是, 为了防止滥用, 与注销账户相同的昵称/账户地址/已认证的号码, 自注销日起, 90天内无法再申请注册。',
    q9: '注销后什么时候可以重新认证相同的号码？',
    a9: '被已注销账户验证过的号码, 自注销日起, 90天以后, 可以重新用于号码验证。',
  },
  'zh-TW': {
    header: '您需要什麼幫助？',
    navBar: {
      all: '全部',
      vote: '投票',
      photos: '圖片',
      fanfic: '王道文',
      accounts: '賬戶',
    },
    q1: 'Fanplus提供怎樣的服務?',
    a1: 'Fanplus是以最愛偶像相同的粉絲為對象, 提供多樣化信息和通訊功能的全面追星的應用程序。 唯一在生日/紀念日可以免費為偶像投票。 在Fanplus中體驗追星的快樂。',
    q2: '如何參加投票?',
    a2: '您可以通過應用內出勤簽到和邀請好友獲得金幣, 且無需付費。 將您獲得的金幣兌換為投票券後, 為您最喜歡的偶像投票。',
    q3: '廣告何時/如何投放?',
    a3: '每月以生日/週年紀念日投票和按主題投票進行。 根據投票結果, 廣告將以在粉絲提交的素材中, 獲得票數最多的素材進行投放。',
    q4: '什麼時候開始準備投票?',
    a4: '投票於相應生日的2個月前開始進行。 主題投票通過Twitter公佈候選人, 請參閱公告。 轉到Fanplus Twitter',
    twitter: '推特(Twitter)',
    q5: '如何使用圖片功能？',
    a5: '查看並下載和自己的最愛偶像相同的粉絲上傳發布的圖片。 如果有喜歡的圖片, 可以直接設置成牆紙。',
    q6: '什麼是視覺王道文?',
    a6: '與現有的線型幻想不同, 它是一種以背景/角色/台詞組成的場面（場景）作為故事情節的方式進行。',
    q7: '',
    a7: '',
    q8: '註銷Fanplus後, 什麼時候可以重新註冊?',
    a8: '註銷後可以立即重新註冊。 只是, 為了防止濫用, 與註銷賬戶相同的暱稱/賬戶地址/已認證的號碼, 自註銷日起, 90天內無法再申請註冊。',
    q9: '註銷後什麼時候可以重新認證相同的號碼？',
    a9: '被已註銷賬戶驗證過的號碼, 自註銷日起, 90天以後, 可以重新用於號碼驗證。',
  },
};
