import type { LangStringType } from '@/types/common';
import type { FooterTextType } from '@/types/textTypes';

export const footerTexts: LangStringType<FooterTextType> = {
  ko: {
    customerService: '고객센터',
    emailButton: '이메일 문의',
    termsOfService: '이용약관',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service_ko.html',
    privacyPolicy: '개인정보처리방침',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy_ko.html',
    introduction: '서울시 강남구 역삼로3길 17-6, 10층',
    copyright: 'Copyright © 팬플러스. All Rights Reserved.',
  },
  en: {
    customerService: 'CS center',
    emailButton: 'Contact',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  es: {
    customerService: 'CS center',
    emailButton: 'Contact',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  in: {
    customerService: 'CS center',
    emailButton: 'Contact',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  ja: {
    customerService: 'CS center',
    emailButton: 'Contact',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  vi: {
    customerService: 'CS center',
    emailButton: 'Contact',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  'zh-CN': {
    customerService: '客户服务中心',
    emailButton: '咨询',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
  'zh-TW': {
    customerService: '客戶服務中心',
    emailButton: '咨询',
    termsOfService: 'Terms of service',
    termsOfServiceLink: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyLink: 'https://privacy.fanplus.co.kr/privacy.html',
    introduction: '10F 17-6, Yeoksam-ro 3-gil, Gangnam-gu, Seoul, Korea',
    copyright: 'Copyright © FanPlus. All Rights Reserved.',
  },
};
