import type { MainPageTextType } from '@/types/textTypes';
import type { LangStringType } from '@/types/common';

export const mainPageTexts: LangStringType<MainPageTextType> = {
  ko: {
    Area1: {
      line1: '덕질에 즐거움 더하기,',
      line2: '팬플러스',
      line3: '',
    },
    Area2: {
      title1: '따로 또 같이, 덕질을 즐기는 다양한 방법',
      title2: '',
      line1: '팬플러스는 최애가 같은 팬들끼리',
      bold_line1: '',
      bold_line2_front: '어떻게 하면 더 즐겁게 덕질할 수 있을지 ',
      line2: '고민합니다.',
      bold_line2_back: '',
      line3: '유료 결제 없는 투표 앱으로 시작해,',
      line4: '함께하는 덕질의 재미를 느낄 수 있도록',
      line5: '팬플러스만의 공간을 만들어가고 있어요.',
      line6: '나와 마음이 맞는 팬들을 만나 덕질에 즐거움을 더해보세요.',
      line7: '',
    },
    Area3: {
      title: '01 내 최애를 주인공으로',
      line1: '매달 새롭게 열리는 다양한 주제의 투표를 확인해보세요.',
      line2: '',
      line3: '팬플러스만의 유료 결제 없는 투표에 참여하고,',
      line4: '최애에게 전 세계 광고를 선물하세요.',
      Ad_title: '[팬플러스 투표 1등 광고상품]',
      Ad1: '미국 타임스퀘어',
      Ad2: '중국 닝보',
      Ad3: '인천공항',
      img: '/images/서비스소개_01_투표썸네일.png',
    },
    Area4: {
      title1: '02 시간 순삭 덕질 콘텐츠',
      title2: '',
      line1: '최애의 고화질 사진과 팬픽 감상은 덤!',
      line2: '나와 최애가 같은 팬들이 공유하는',
      line3: '다양한 콘텐츠를 즐겨보세요.',
      plus: '북적이는 게시판도 방문해보세요.',
      img1: '/images/서비스소개_02_게시판.png',
      img2: '/images/서비스소개_02_사진.png',
      img3: '/images/서비스소개_02_팬픽.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹.png',
    },
    Area5: {
      title1: '03 덕질, 어디까지 해봤나요?',
      title2: '',
      line1: '덕질할 수록 쌓이는 팬플러스만의 활동 배지!',
      line2: '배지를 수집하는 재미와 함께',
      line3: '최애를 향한 나의 덕력을 확인해보세요.',
      line4: '',
      plus1: '다른 사람의 활동 배지를 보면 그 사람의 덕질 성향도 알 수 있어요.',
      plus2: '',
      img1: '/images/서비스소개_03_보유배지-1.png',
      img2: '/images/서비스소개_03_프로필-1.png',
      img3: '/images/서비스소개_03_미션배지상세-1.png',
      img4: '/images/서비스소개_03_업적배지상세-1.png',
    },
    Area6: {
      title1: '04 함께하면 더 즐거운 덕질',
      title2: '',
      line1: '나와 성향이 비슷한 친구를 발견했다면?',
      line2: '실시간 채팅으로 최애 이야기를 나눠보세요.',
      line3: '혹시 알아요?',
      line4: '팬플러스에서 인생 덕메를 만나게 될지!',
      img1: '/images/서비스소개_04_친구.png',
      img2: '/images/서비스소개_04_채팅.png',
    },
  },
  en: {
    Area1: {
      line1: 'Must-Have App for',
      line2: 'Worldwide Kpop Fans',
      line3: 'FanPlus',
    },
    Area2: {
      title1: 'Be together with worldwide fans',
      title2: '& add more fun to your fan life',
      line1: 'Fanplus considers',
      bold_line1: ' the fun of fan life',
      bold_line2_front: '',
      line2: 'with other fan friends the most valuable experience',
      bold_line2_back: '',
      line3: 'Starting with a voting app without payment,',
      line4: 'we are creating a community-friendly space,',
      line5: 'so all fans have fun being together.',
      line6: 'Meet fan friends who just hit it off with you on FanPlus',
      line7: 'and add joy to your fan life',
    },
    Area3: {
      title: '01 Promote your star',
      line1: 'Check out votes with a variety of new topics',
      line2: 'every month.',
      line3: 'Participate in Fan Plus votes with no-payment',
      line4: 'and give reward ADs to your star around the world',
      Ad_title: '[FanPlus Reward ADs]',
      Ad1: 'NYC Times Square in the US',
      Ad2: 'Ningbo in China',
      Ad3: 'Incheon Airport in Korea',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 Enjoy entertaining',
      title2: 'contents',
      line1: 'Check high-quality photos and fanfic of your star!',
      line2: 'Enjoy varied contents',
      line3: 'that users create and share together.',
      plus: "Don't miss the board too!",
      img1: '/images/서비스소개_02_게시판_en.png',
      img2: '/images/서비스소개_02_사진_en.png',
      img3: '/images/서비스소개_02_팬픽_en.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_en.png',
    },
    Area5: {
      title1: '03 How enthusiastic fan',
      title2: 'are you?',
      line1: 'The more active you are,',
      line2: 'the more badges you get on FanPlus!',
      line3: 'Show your badges to your friends',
      line4: 'so everyone knows how much you support your star.',
      plus1: "Check your friend's stan propensity with badges on FanPlus.",
      plus2: '',
      img1: '/images/서비스소개_03_보유배지_en.png',
      img2: '/images/서비스소개_03_프로필_en.png',
      img3: '/images/서비스소개_03_미션배지상세_en.png',
      img4: '/images/서비스소개_03_업적배지상세_en.png',
    },
    Area6: {
      title1: '04 It is more fun',
      title2: 'when we are all together',
      line1: 'If you just hit it off with fan friends,',
      line2: 'chat and share your fan life with them.',
      line3: 'Who knows?',
      line4: 'You will find the BFF on FanPlus!',
      img1: '/images/서비스소개_04_친구_en.png',
      img2: '/images/서비스소개_04_채팅_en.png',
    },
  },
  es: {
    Area1: {
      line1: 'Must-Have App for',
      line2: 'Worldwide Kpop Fans',
      line3: 'FanPlus',
    },
    Area2: {
      title1: 'Be together with worldwide fans',
      title2: '& add more fun to your fan life',
      line1: 'Fanplus considers',
      bold_line1: ' the fun of fan life',
      bold_line2_front: '',
      line2: 'with other fan friends the most valuable experience',
      bold_line2_back: '',
      line3: 'Starting with a voting app without payment,',
      line4: 'we are creating a community-friendly space,',
      line5: 'so all fans have fun being together.',
      line6: 'Meet fan friends who just hit it off with you on FanPlus',
      line7: 'and add joy to your fan life',
    },
    Area3: {
      title: '01 Promote your star',
      line1: 'Check out votes with a variety of new topics',
      line2: 'every month.',
      line3: 'Participate in Fan Plus votes with no-payment',
      line4: 'and give reward ADs to your star around the world',
      Ad_title: '[FanPlus Reward ADs]',
      Ad1: 'NYC Times Square in the US',
      Ad2: 'Ningbo in China',
      Ad3: 'Incheon Airport in Korea',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 Enjoy entertaining',
      title2: 'contents',
      line1: 'Check high-quality photos and fanfic of your star!',
      line2: 'Enjoy varied contents',
      line3: 'that users create and share together.',
      plus: "Don't miss the board too!",
      img1: '/images/서비스소개_02_게시판_en.png',
      img2: '/images/서비스소개_02_사진_en.png',
      img3: '/images/서비스소개_02_팬픽_en.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_en.png',
    },
    Area5: {
      title1: '03 How enthusiastic fan',
      title2: 'are you?',
      line1: 'The more active you are,',
      line2: 'the more badges you get on FanPlus!',
      line3: 'Show your badges to your friends',
      line4: 'so everyone knows how much you support your star.',
      plus1: "Check your friend's stan propensity with badges on FanPlus.",
      plus2: '',
      img1: '/images/서비스소개_03_보유배지_en.png',
      img2: '/images/서비스소개_03_프로필_en.png',
      img3: '/images/서비스소개_03_미션배지상세_en.png',
      img4: '/images/서비스소개_03_업적배지상세_en.png',
    },
    Area6: {
      title1: '04 It is more fun',
      title2: 'when we are all together',
      line1: 'If you just hit it off with fan friends,',
      line2: 'chat and share your fan life with them.',
      line3: 'Who knows?',
      line4: 'You will find the BFF on FanPlus!',
      img1: '/images/서비스소개_04_친구_en.png',
      img2: '/images/서비스소개_04_채팅_en.png',
    },
  },
  in: {
    Area1: {
      line1: 'Must-Have App for',
      line2: 'Worldwide Kpop Fans',
      line3: 'FanPlus',
    },
    Area2: {
      title1: 'Be together with worldwide fans',
      title2: '& add more fun to your fan life',
      line1: 'Fanplus considers',
      bold_line1: ' the fun of fan life',
      bold_line2_front: '',
      line2: 'with other fan friends the most valuable experience',
      bold_line2_back: '',
      line3: 'Starting with a voting app without payment,',
      line4: 'we are creating a community-friendly space,',
      line5: 'so all fans have fun being together.',
      line6: 'Meet fan friends who just hit it off with you on FanPlus',
      line7: 'and add joy to your fan life',
    },
    Area3: {
      title: '01 Promote your star',
      line1: 'Check out votes with a variety of new topics',
      line2: 'every month.',
      line3: 'Participate in Fan Plus votes with no-payment',
      line4: 'and give reward ADs to your star around the world',
      Ad_title: '[FanPlus Reward ADs]',
      Ad1: 'NYC Times Square in the US',
      Ad2: 'Ningbo in China',
      Ad3: 'Incheon Airport in Korea',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 Enjoy entertaining',
      title2: 'contents',
      line1: 'Check high-quality photos and fanfic of your star!',
      line2: 'Enjoy varied contents',
      line3: 'that users create and share together.',
      plus: "Don't miss the board too!",
      img1: '/images/서비스소개_02_게시판_en.png',
      img2: '/images/서비스소개_02_사진_en.png',
      img3: '/images/서비스소개_02_팬픽_en.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_en.png',
    },
    Area5: {
      title1: '03 How enthusiastic fan',
      title2: 'are you?',
      line1: 'The more active you are,',
      line2: 'the more badges you get on FanPlus!',
      line3: 'Show your badges to your friends',
      line4: 'so everyone knows how much you support your star.',
      plus1: "Check your friend's stan propensity with badges on FanPlus.",
      plus2: '',
      img1: '/images/서비스소개_03_보유배지_en.png',
      img2: '/images/서비스소개_03_프로필_en.png',
      img3: '/images/서비스소개_03_미션배지상세_en.png',
      img4: '/images/서비스소개_03_업적배지상세_en.png',
    },
    Area6: {
      title1: '04 It is more fun',
      title2: 'when we are all together',
      line1: 'If you just hit it off with fan friends,',
      line2: 'chat and share your fan life with them.',
      line3: 'Who knows?',
      line4: 'You will find the BFF on FanPlus!',
      img1: '/images/서비스소개_04_친구_en.png',
      img2: '/images/서비스소개_04_채팅_en.png',
    },
  },
  ja: {
    Area1: {
      line1: 'Must-Have App for',
      line2: 'Worldwide Kpop Fans',
      line3: 'FanPlus',
    },
    Area2: {
      title1: 'Be together with worldwide fans',
      title2: '& add more fun to your fan life',
      line1: 'Fanplus considers',
      bold_line1: ' the fun of fan life',
      bold_line2_front: '',
      line2: 'with other fan friends the most valuable experience',
      bold_line2_back: '',
      line3: 'Starting with a voting app without payment,',
      line4: 'we are creating a community-friendly space,',
      line5: 'so all fans have fun being together.',
      line6: 'Meet fan friends who just hit it off with you on FanPlus',
      line7: 'and add joy to your fan life',
    },
    Area3: {
      title: '01 Promote your star',
      line1: 'Check out votes with a variety of new topics',
      line2: 'every month.',
      line3: 'Participate in Fan Plus votes with no-payment',
      line4: 'and give reward ADs to your star around the world',
      Ad_title: '[FanPlus Reward ADs]',
      Ad1: 'NYC Times Square in the US',
      Ad2: 'Ningbo in China',
      Ad3: 'Incheon Airport in Korea',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 Enjoy entertaining',
      title2: 'contents',
      line1: 'Check high-quality photos and fanfic of your star!',
      line2: 'Enjoy varied contents',
      line3: 'that users create and share together.',
      plus: "Don't miss the board too!",
      img1: '/images/서비스소개_02_게시판_en.png',
      img2: '/images/서비스소개_02_사진_en.png',
      img3: '/images/서비스소개_02_팬픽_en.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_en.png',
    },
    Area5: {
      title1: '03 How enthusiastic fan',
      title2: 'are you?',
      line1: 'The more active you are,',
      line2: 'the more badges you get on FanPlus!',
      line3: 'Show your badges to your friends',
      line4: 'so everyone knows how much you support your star.',
      plus1: "Check your friend's stan propensity with badges on FanPlus.",
      plus2: '',
      img1: '/images/서비스소개_03_보유배지_en.png',
      img2: '/images/서비스소개_03_프로필_en.png',
      img3: '/images/서비스소개_03_미션배지상세_en.png',
      img4: '/images/서비스소개_03_업적배지상세_en.png',
    },
    Area6: {
      title1: '04 It is more fun',
      title2: 'when we are all together',
      line1: 'If you just hit it off with fan friends,',
      line2: 'chat and share your fan life with them.',
      line3: 'Who knows?',
      line4: 'You will find the BFF on FanPlus!',
      img1: '/images/서비스소개_04_친구_en.png',
      img2: '/images/서비스소개_04_채팅_en.png',
    },
  },
  vi: {
    Area1: {
      line1: 'Must-Have App for',
      line2: 'Worldwide Kpop Fans',
      line3: 'FanPlus',
    },
    Area2: {
      title1: 'Be together with worldwide fans',
      title2: '& add more fun to your fan life',
      line1: 'Fanplus considers',
      bold_line1: ' the fun of fan life',
      bold_line2_front: '',
      line2: 'with other fan friends the most valuable experience',
      bold_line2_back: '',
      line3: 'Starting with a voting app without payment,',
      line4: 'we are creating a community-friendly space,',
      line5: 'so all fans have fun being together.',
      line6: 'Meet fan friends who just hit it off with you on FanPlus',
      line7: 'and add joy to your fan life',
    },
    Area3: {
      title: '01 Promote your star',
      line1: 'Check out votes with a variety of new topics',
      line2: 'every month.',
      line3: 'Participate in Fan Plus votes with no-payment',
      line4: 'and give reward ADs to your star around the world',
      Ad_title: '[FanPlus Reward ADs]',
      Ad1: 'NYC Times Square in the US',
      Ad2: 'Ningbo in China',
      Ad3: 'Incheon Airport in Korea',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 Enjoy entertaining',
      title2: 'contents',
      line1: 'Check high-quality photos and fanfic of your star!',
      line2: 'Enjoy varied contents',
      line3: 'that users create and share together.',
      plus: "Don't miss the board too!",
      img1: '/images/서비스소개_02_게시판_en.png',
      img2: '/images/서비스소개_02_사진_en.png',
      img3: '/images/서비스소개_02_팬픽_en.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_en.png',
    },
    Area5: {
      title1: '03 How enthusiastic fan',
      title2: 'are you?',
      line1: 'The more active you are,',
      line2: 'the more badges you get on FanPlus!',
      line3: 'Show your badges to your friends',
      line4: 'so everyone knows how much you support your star.',
      plus1: "Check your friend's stan propensity with badges on FanPlus.",
      plus2: '',
      img1: '/images/서비스소개_03_보유배지_en.png',
      img2: '/images/서비스소개_03_프로필_en.png',
      img3: '/images/서비스소개_03_미션배지상세_en.png',
      img4: '/images/서비스소개_03_업적배지상세_en.png',
    },
    Area6: {
      title1: '04 It is more fun',
      title2: 'when we are all together',
      line1: 'If you just hit it off with fan friends,',
      line2: 'chat and share your fan life with them.',
      line3: 'Who knows?',
      line4: 'You will find the BFF on FanPlus!',
      img1: '/images/서비스소개_04_친구_en.png',
      img2: '/images/서비스소개_04_채팅_en.png',
    },
  },
  'zh-CN': {
    Area1: {
      line1: '在追星的快乐中,',
      line2: '加上Fanplus',
      line3: '',
    },
    Area2: {
      title1: '单独或一起, 多种快乐的追星方法',
      title2: '',
      line1: 'Fanplus正在考虑,',
      bold_line1: '',
      bold_line2_front: '',
      line2: '如何让最活跃的',
      bold_line2_back: '粉丝之间更加快乐地追星。',
      line3: '从免费投票的APP开始,',
      line4: '为了让粉丝们可以一起体会追星的快乐，',
      line5: 'Fanplus正在打造属于自己的追星空间。',
      line6: '结识与自己心心相通的歌迷, 在追星中增添更多的快乐。',
      line7: '',
    },
    Area3: {
      title: '01 让我的最爱成为主人公',
      line1: '每月查看新主题的相关投票。',
      line2: '',
      line3: '参加Fanplus的独家免费投票,',
      line4: '给最喜爱的明星做全球广告。',
      Ad_title: '[Fanplus投票冠军广告商品]',
      Ad1: '美国时代广场',
      Ad2: '中国宁波',
      Ad3: '韩国仁川机场',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 实时追星信息',
      title2: '',
      line1: '最爱偶像的高清图片附加欣赏王道文！',
      line2: '与自己最爱相同的粉丝分享各种信息。',
      line3: '',
      plus: '请访问活跃的公告栏。',
      img1: '/images/서비스소개_02_게시판_zh-cn.png',
      img2: '/images/서비스소개_02_사진_zh-cn.png',
      img3: '/images/서비스소개_02_팬픽_zh-cn.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_zh-cn.png',
    },
    Area5: {
      title1: '03 追星，您做过哪些?',
      title2: '',
      line1: '追星积攒Fanplus独特的活动徽章！',
      line2: '与收集徽章的乐趣一起,',
      line3: '了解自己对最爱偶像的追逐热情。',
      line4: '',
      plus1: '如果您查看其他人的活动徽章时,',
      plus2: '还可以知道他们的追星趋向。',
      img1: '/images/서비스소개_03_보유배지_zh-cn.png',
      img2: '/images/서비스소개_03_프로필_zh-cn.png',
      img3: '/images/서비스소개_03_미션배지상세_zh-cn.png',
      img4: '/images/서비스소개_03_업적배지상세_zh-cn.png',
    },
    Area6: {
      title1: '04 一起追星更加快乐',
      title2: '',
      line1: '发现与自己追星趋势相似的朋友？',
      line2: '在实时聊天中, 分享您最爱偶像的点点滴滴',
      line3: '您知道吗？',
      line4: '您或许能在Fanplus中遇到人生的追星盟友呢！',
      img1: '/images/서비스소개_04_친구_zh-cn.png',
      img2: '/images/서비스소개_04_채팅_zh-cn.png',
    },
  },
  'zh-TW': {
    Area1: {
      line1: '在追星的快樂中,',
      line2: '加上Fanplus',
      line3: '',
    },
    Area2: {
      title1: '單獨或一起，多種快樂的追星方法',
      title2: '',
      line1: 'Fanplus正在考慮,',
      bold_line1: '',
      bold_line2_front: '',
      line2: '如何讓最活躍的',
      bold_line2_back: '粉絲之間更加快樂地追星。',
      line3: '從免費投票的APP開始,',
      line4: '為了讓粉絲們可以一起體會追星的快樂，',
      line5: 'Fanplus正在打造屬於自己的追星空間。',
      line6: '結識與自己心心相通的歌迷, 在追星中增添更多的快樂。',
      line7: '',
    },
    Area3: {
      title: '01 讓我的最愛成為主人公',
      line1: '每月查看新主題的相關投票。',
      line2: '',
      line3: '參加Fanplus的獨家免費投票,',
      line4: '給最喜愛的明星做全球廣告。',
      Ad_title: '[Fanplus投票冠軍廣告商品]',
      Ad1: '美國時代廣場',
      Ad2: '中國寧波',
      Ad3: '韓國仁川機場',
      img: '/images/서비스소개_01_투표썸네일_en.png',
    },
    Area4: {
      title1: '02 實時追星信息',
      title2: '',
      line1: '最愛偶像的高清圖片附加欣賞王道文！',
      line2: '與自己最愛相同的粉絲分享各種信息。',
      line3: '',
      plus: '請訪問活躍的公告欄。',
      img1: '/images/서비스소개_02_게시판_zh-tw.png',
      img2: '/images/서비스소개_02_사진_zh-tw.png',
      img3: '/images/서비스소개_02_팬픽_zh-tw.png',
      img4: '/images/서비스소개_02_왕중왕전랭킹_zh-tw.png',
    },
    Area5: {
      title1: '03 追星，您做過哪些?',
      title2: '',
      line1: '追星積攢Fanplus獨特的活動徽章！',
      line2: '與收集徽章的樂趣一起,',
      line3: '了解自己對最愛偶像的追逐熱情。',
      line4: '',
      plus1: '如果您查看其他人的活動徽章時,',
      plus2: '還可以知道他們的追星趨向。',
      img1: '/images/서비스소개_03_보유배지_zh-tw.png',
      img2: '/images/서비스소개_03_프로필_zh-tw.png',
      img3: '/images/서비스소개_03_미션배지상세_zh-tw.png',
      img4: '/images/서비스소개_03_업적배지상세_zh-tw.png',
    },
    Area6: {
      title1: '04 一起追星更加快樂',
      title2: '',
      line1: '發現與自己追星趨勢相似的朋友？',
      line2: '在實時聊天中, 分享您最愛偶像的點點滴滴',
      line3: '您知道嗎？',
      line4: '您或許能在Fanplus中遇到人生的追星盟友呢！',
      img1: '/images/서비스소개_04_친구_zh-tw.png',
      img2: '/images/서비스소개_04_채팅_zh-tw.png',
    },
  },
};
