import type { NavBarTextType } from '@/types/textTypes';
import type { LangStringType } from '@/types/common';

export const navBarTexts: LangStringType<NavBarTextType> = {
  ko: {
    vote: '투표',
    community: '커뮤니티',
    aboutUs: '서비스 소개',
    recruit: '채용',
    business: '제휴 문의',
    language: '한국어',
    link: {
      vote: '/ko/votes',
      community: '/ko/community',
      aboutUs: '/ko/',
      business: '/ko/business',
      faq: '/ko/faq',
    },
  },
  en: {
    vote: 'Vote',
    community: 'Community',
    aboutUs: 'About Us',
    recruit: '',
    business: 'Business Inquiry',
    language: 'English',
    link: {
      vote: '/en/votes',
      community: '/en/community',
      aboutUs: '/en',
      business: '/en/business',
      faq: '/en/faq',
    },
  },
  es: {
    vote: 'Votación',
    community: 'Comunidad',
    aboutUs: 'About Us',
    recruit: '',
    business: 'Business Inquiry',
    language: 'Español',
    link: {
      vote: '/es/votes',
      community: '/es/community',
      aboutUs: '/es',
      business: '/es/business',
      faq: '/es/faq',
    },
  },
  in: {
    vote: 'Vote',
    community: 'Komunitas',
    aboutUs: 'About Us',
    recruit: '',
    business: 'Business Inquiry',
    language: 'Bahasa Indonesia',
    link: {
      vote: '/in/votes',
      community: '/in/community',
      aboutUs: '/in',
      business: '/in/business',
      faq: '/in/faq',
    },
  },
  ja: {
    vote: '投票',
    community: 'コミュニティ',
    aboutUs: 'About Us',
    recruit: '',
    business: 'Business Inquiry',
    language: '日本語',
    link: {
      vote: '/ja/votes',
      community: '/ja/community',
      aboutUs: '/ja',
      business: '/ja/business',
      faq: '/ja/faq',
    },
  },
  vi: {
    vote: 'Bỏ phiếu',
    community: 'Cộng đồng',
    aboutUs: 'About Us',
    recruit: '',
    business: 'Business Inquiry',
    language: 'Tiếng việt',
    link: {
      vote: '/vi/votes',
      community: '/vi/community',
      aboutUs: '/vi',
      business: '/vi/business',
      faq: '/vi/faq',
    },
  },
  'zh-CN': {
    vote: '投票',
    community: '社区',
    aboutUs: '服务介绍',
    recruit: '',
    business: '商务咨询',
    language: '中文(简体)',
    link: {
      vote: '/zh-CN/votes',
      community: '/zh-CN/community',
      aboutUs: '/zh-CN',
      business: '/zh-CN/business',
      faq: '/zh-CN/faq',
    },
  },
  'zh-TW': {
    vote: '投票',
    community: '社區',
    aboutUs: '服務介紹',
    recruit: '',
    business: '商務諮詢',
    language: '中文(繁體)',
    link: {
      vote: '/zh-TW/votes',
      community: '/zh-TW/community',
      aboutUs: '/zh-TW',
      business: '/zh-TW/business',
      faq: '/zh-TW/faq',
    },
  },
};
