import type { SignUpPageTextType } from '@/types/textTypes';
import type { LangStringType } from '@/types/common';

export const signupPageTexts: LangStringType<SignUpPageTextType> = {
  ko: {
    heading: '이용약관',
    line1: '원활한 서비스 이용을 위해 동의해주세요.',
    agree1: '만 14세 이상입니다. (필수)',
    agree2: '서비스 이용약관 (필수)',
    agree3: '개인정보 취급방침 (필수)',
    agree4: '개인정보 제3자 제공 (필수)',
    detail: '보기',
    start: '시작',
    agreeAll: '모두 동의하기',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service_ko.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy_ko.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties_ko.html',
  },
  en: {
    heading: 'Terms of Service',
    line1: 'Please agree to the terms and conditions.',
    agree1: "I'm 14 years or older (required)",
    agree2: 'Terms of service (required)',
    agree3: 'Privacy Policy (required)',
    agree4: 'Privacy Terms and Conditions: third parties (required)',
    detail: 'Details',
    start: 'Start',
    agreeAll: 'I agree all',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  es: {
    heading: 'Términos y Condiciones',
    line1: 'Por favor, acepta usar el servicio sin problemas.',
    agree1: 'Tengo 14 años o más. (Obligatorio)',
    agree2: 'Términos y Condiciones del servicio (Obligatorio)',
    agree3: 'Política de privacidad de información personal (Obligatorio)',
    agree4: 'Suministro de información a terceros (Obligatorio)</b>',
    detail: 'Ver detalles',
    start: 'Iniciar',
    agreeAll: 'Aceptar todo',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  in: {
    heading: 'Persetujuan Penggunaan',
    line1: 'Harap setujui persyaratan dan ketentuan.',
    agree1: 'Aku 14 tahun atau lebih tua (yg dibutuhkan)',
    agree2: 'Ketentuan layanan (yg dibutuhkan)',
    agree3: 'Kebijakan pribadi (yg dibutuhkan)',
    agree4: 'Pemberian Informasi kepada Pihak Ketiga (yg dibutuhkan)',
    detail: 'Details',
    start: 'Mulailah',
    agreeAll: 'Saya setuju semua',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  ja: {
    heading: '利用規約',
    line1: '円滑なサービスの利用のために同意してください。',
    agree1: '私は14歳以上です(必須)',
    agree2: 'サービス利用約款 (必須)',
    agree3: '個人情報取扱方針 (必須)',
    agree4: '個人情報の第三者提供 (必須)',
    detail: '続きを読む',
    start: '詩作',
    agreeAll: '同意(必須)',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  vi: {
    heading: 'Điều khoản sử dụng',
    line1: 'Vui lòng đồng ý với các điều khoản và điều kiện.',
    agree1: 'Tôi từ 14 tuổi trở lên(bắt buộc)',
    agree2: 'Điều khoản dịch vụ (bắt buộc)',
    agree3: 'Chính sách bảo mật (bắt buộc)',
    agree4: 'Cung cấp thông tin cho các bên thứ ba (bắt buộc)',
    detail: 'Chi tiết',
    start: 'Khởi đầu',
    agreeAll: 'Tôi đồng ý tất cả',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  'zh-CN': {
    heading: '用户协议',
    line1: '为顺利使用该服务，请同意条款。',
    agree1: '我是14岁及以上 (必选)',
    agree2: '服务条款 (必选)',
    agree3: '个人隐私政策 (必选)',
    agree4: '第三方隐私政策 (必选)',
    detail: '查看详情',
    start: '开始',
    agreeAll: '全部同意',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
  'zh-TW': {
    heading: '用戶協議',
    line1: '為順利使用該服務，請同意條款。',
    agree1: '我是14歲及以上(必選)',
    agree2: '服務條款 (必選)',
    agree3: '個人隱私政策 (必選)',
    agree4: '第三方隱私政策 (必選)',
    detail: '查看詳情',
    start: '開始',
    agreeAll: '全部同意',
    agree2Link: 'https://privacy.fanplus.co.kr/terms_of_service.html',
    agree3Link: 'https://privacy.fanplus.co.kr/privacy.html',
    agree4Link: 'https://privacy.fanplus.co.kr/thrid_parties.html',
  },
};
