import type { VotesPageTextType } from '@/types/textTypes';
import type { LangStringType } from '@/types/common';

export const votesPageTexts: LangStringType<VotesPageTextType> = {
  ko: {
    voteEnd: '투표 종료까지',
    voteFinished: '투표 종료',
    voteStart: '투표 시작까지',
    tab: {
      all: '전체',
      bday: '생일 투표',
      league: '리그전',
    },
    winner: '1위',
    daysAgo: '일',
    hoursAgo: '시',
    minutesAgo: '분',
  },
  en: {
    voteEnd: 'Until the end',
    voteFinished: 'The vote has been closed',
    voteStart: 'Until the open',
    tab: {
      all: 'ALL',
      bday: 'B-day',
      league: 'League',
    },
    winner: '1st',
    daysAgo: 'd',
    hoursAgo: 'h',
    minutesAgo: 'm',
  },
  es: {
    voteEnd: 'Termina en',
    voteFinished: 'La votación está cerrada.',
    voteStart: 'hasta la apertura',
    tab: {
      all: 'ALL',
      bday: 'B-day',
      league: 'League',
    },
    winner: 'Primer puesto',
    daysAgo: 'Día',
    hoursAgo: 'Hora',
    minutesAgo: 'Minuto',
  },
  in: {
    voteEnd: 'Sampai akhir',
    voteFinished: 'Pemungutan suara sudah selesai.',
    voteStart: 'Sampai tempat terbuka',
    tab: {
      all: 'ALL',
      bday: 'B-day',
      league: 'League',
    },
    winner: '1st',
    daysAgo: 'd',
    hoursAgo: 'h',
    minutesAgo: 'm',
  },
  ja: {
    voteEnd: '最後まで',
    voteFinished: '投票が締め切られました。',
    voteStart: 'オープンまで',
    tab: {
      all: 'ALL',
      bday: '誕生日 投票',
      league: 'リーグ 投票',
    },
    winner: '1位',
    daysAgo: '日々',
    hoursAgo: '時間',
    minutesAgo: '分',
  },
  vi: {
    voteEnd: 'Cho đến khi kết thúc',
    voteFinished: 'Hết hạn bỏ phiếu',
    voteStart: 'cho đến khi khai trương',
    tab: {
      all: 'ALL',
      bday: 'B-day',
      league: 'League',
    },
    winner: '1st',
    daysAgo: 'ngày',
    hoursAgo: 'giờ',
    minutesAgo: 'từ phút',
  },
  'zh-CN': {
    voteEnd: '距离投票截止还有',
    voteFinished: '投票已结束',
    voteStart: '离公开投票还有一段距离',
    tab: {
      all: 'ALL',
      bday: '生日投票',
      league: '联赛',
    },
    winner: '1位',
    daysAgo: '天',
    hoursAgo: '小时',
    minutesAgo: '分',
  },
  'zh-TW': {
    voteEnd: '距離投票截止還有',
    voteFinished: '投票已結束',
    voteStart: '離公開投票還有一段距離',
    tab: {
      all: 'ALL',
      bday: '生日投票',
      league: '聯賽',
    },
    winner: '1位',
    daysAgo: '天',
    hoursAgo: '小時',
    minutesAgo: '分',
  },
};
