export const getVotes = (
  vote_type: string | undefined | null,
  page: number,
  per_page: number,
  lang: string
) => {
  const response = fetch(
    `https://napi.appphotocard.com/v2/votes/votes?vote_type=${vote_type}&page=${page}&per_page=${per_page}&lang=${lang}`,
    {
      method: 'GET',
      headers: {
        Authorization: `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMyIsImp0aSI6ImY5NjVjZDg3N2MyMTNkZjYwZWU2NDViMjYxZWJhYjcxMWRkYjIxZTE3OGExOTdjMmQ5NzY1ZTNkYTUyNDI2MDU1Y2QzYWFmMGE5ZTQxODljIiwiaWF0IjoxNjg4MDI0NTEzLjMzMzY4OCwibmJmIjoxNjg4MDI0NTEzLjMzMzY5MSwiZXhwIjoxNzE5NjQ2OTEzLjMxNTE3LCJzdWIiOiIxNzUiLCJzY29wZXMiOltdfQ.bKebFWEEu2ruQS0aj0wbjU3MWldP7lcJdesoiLxVZcf1cMFiOCGjKW2SNmCDCGUMckVu-SWZTpIRs-7YBsa6Ag3BjYMdxjlpzd7iyx3wBnkV4nJDSV46o9DFwGP2_4T9wyiVms1X3kgmW6W0o_domAtFAk5l_ny4s5cdO5faZOSj7weSdgSmLz69PxwrsJZgM-Z24flOB40TiIMgcvA_nzA7sIBe8P_PljpEUZYYXMlcn4V1yGoj_eyJOsFvV88Ep8HRF3hya6DPAs2Q1cwQcaTkchShzO3xYgkqtGhQ6NxBB7nmjpBMQyUhf1HYfLFDH7eWCwWJkUNc8YduvzatvP7wDWWc_h4dpMutMjtwQbjJLFj5bsl5VSpVkW8ev3_ASS97NxNtY6OcUxTrsm0oFCiScy_yDMqXWR3Ym3KJz_Sj4yWujtQ-2Yo4AKih2IlteGX0rTInNQtuk0eKaGF_jQaeIbEx9OWoWM9Akquy1EULcO3Vtzjzqf54fj5H3MkjdkrH5prRh_cBJvB_viNnCLswy3aKnf5QEFRr7I2--8SEw5Y21bHf6B10ol7AvegoYFMS3o3Cy9SrP6YpvAmRzLYnco-8TaRw0a1QgyGGywSxiL2wiVQXbCoK95qwK9FhBProc5xJd0NYgb_7NYDQJ4Ii3ZX3u7TMYZSi56vlkMM`,
      },
    }
  );
  return response;
};

export const getVoteDetail = () => {
  const response = {
    RESULTS: {
      ERROR: 0,
      MSG: 'success',
      DATAS: {
        VOTE_INFO: {
          TITLE: '1부 리그전 투표 - 남자아이돌 (4회차)',
          TITLE_IMG:
            'https://cdnetphoto.appphotocard.com/vote_thumbnail/208/TITLE_IMG_ko_KR_20230712162629.jpg',
          DESCRIPTION:
            '※ 투표권 획득방법<br/>1. 친구투표권 <br/>2. 친구 초대<br/>3. 광고참여<br/><br/>※ 투표 유의사항<br/>- 생일 및 데뷔 기념일만 후보 등록 가능합니다.<br/>(데뷔 500일 , 믹스테잎 발매일 등 포함 x )<br/>- 현재 그룹활동 중인 멤버의 솔로 데뷔 기념일은 후보로 등록되지 않습니다.<br/>- 그룹 내 유닛활동을 하는 경우 유닛그룹의 기념일은 포함되지 않습니다.<br/>- 해체한 그룹의 기념일은 포함되지 않습니다.<br/>- 배우 및 트로트 장르 가수의 생일 및 기념일은 포함되지 않습니다.<br/>- 공식 데뷔를 하지 않은 연습생 혹은 그룹 해체 및 탈퇴 후 공식적으로 활동 공지가 뜨지 않거나 공식 활동이 없는 멤버의 생일 및 기념일은 포함되지 않습니다. (*공식 활동 : 방송,광고,화보,연기 등 모든 연예 활동)<br/> -한국에서 활동 중인 아이돌 그룹 혹은 가수의 생일 및 데뷔기념일만 등록 가능합니다.<br/>',
          LINK_TXT: "팬플러스 '리그전'이란",
          LINK: 'http://fanplus.co.kr/league_male_4/',
          FINISHED_LINK: 'https://fanplus.co.kr/category/event_eng/',
          FINISHED_BTN_TXT: '광고 보러 가기',
          START_DATE: '2023-07-12 18:00:00',
          END_DATE: '2023-07-25 17:00:00',
          STATUS: 'N',
          LIKE_CNT: '1072',
          COMMENT_CNT: '830',
          TOTAL_VOTE_CNT: '259367784',
          VOTE_CNT_GAP: 22518878,
          FIRST_PRIZE_TITLE: '홍대 공항철도 영상광고(14일)',
          SECOND_PRIZE_TITLE: '서울 지하철역 사각기둥 영상광고(30일)',
          THIRD_PRIZE_TITLE: '서울 지하철역  사각기둥 영상광고(14일)',
          FIRST_PRIZE_DESCRIPTION:
            '모든 광고 디자인은 투표 종료 후 팬 응모 및 투표를 통해 선정합니다.',
          SECOND_PRIZE_DESCRIPTION:
            '모든 광고 디자인은 투표 종료 후 팬 응모 및 투표를 통해 선정합니다.',
          THIRD_PRIZE_DESCRIPTION:
            '모든 광고 디자인은 투표 종료 후 팬 응모 및 투표를 통해 선정합니다.',
          FIRST_PRIZE_IMG:
            'https://cdnetphoto.appphotocard.com/vote_thumbnail/208/FIRST_PRIZE_IMG_ko_KR_20230712164154.png',
          SECOND_PRIZE_IMG:
            'https://cdnetphoto.appphotocard.com/vote_thumbnail/208/SECOND_PRIZE_IMG_ko_KR_20230712164155.png',
          THIRD_PRIZE_IMG:
            'https://cdnetphoto.appphotocard.com/vote_thumbnail/208/THIRD_PRIZE_IMG_ko_KR_20230712164156.png',
          STARS: [
            {
              RANK: '1',
              VOTE_IDX: '208',
              STAR_IDX: '9',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/91.png',
              VOTE_CNT: '77448908',
              TOP_LAYER_IDX: '9',
              STAR_NAME: '디오',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/91.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '2',
              VOTE_IDX: '208',
              STAR_IDX: '16',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1652.png',
              VOTE_CNT: '54930030',
              TOP_LAYER_IDX: '16',
              STAR_NAME: '뷔',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1652.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '3',
              VOTE_IDX: '208',
              STAR_IDX: '770',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7700.png',
              VOTE_CNT: '25964647',
              TOP_LAYER_IDX: '98',
              STAR_NAME: '강다니엘',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7700.png',
              STAR_GROUP_NAME: '강다니엘(Kang Daniel)',
            },
            {
              RANK: '4',
              VOTE_IDX: '208',
              STAR_IDX: '15',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1552.png',
              VOTE_CNT: '21778618',
              TOP_LAYER_IDX: '15',
              STAR_NAME: '지민',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1552.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '5',
              VOTE_IDX: '208',
              STAR_IDX: '11',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1152.png',
              VOTE_CNT: '9186011',
              TOP_LAYER_IDX: '11',
              STAR_NAME: '진',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1152.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '6',
              VOTE_IDX: '208',
              STAR_IDX: '13',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1352.png',
              VOTE_CNT: '7492793',
              TOP_LAYER_IDX: '13',
              STAR_NAME: '제이홉',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1352.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '7',
              VOTE_IDX: '208',
              STAR_IDX: '1147',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1147546.png',
              VOTE_CNT: '6322867',
              TOP_LAYER_IDX: '959',
              STAR_NAME: '니키',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1147546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '8',
              VOTE_IDX: '208',
              STAR_IDX: '17',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1752.png',
              VOTE_CNT: '5562241',
              TOP_LAYER_IDX: '17',
              STAR_NAME: '정국',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1752.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '9',
              VOTE_IDX: '208',
              STAR_IDX: '772',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7720.png',
              VOTE_CNT: '5492137',
              TOP_LAYER_IDX: '192',
              STAR_NAME: '하성운',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7720.png',
              STAR_GROUP_NAME: '하성운(Ha sungwoon)',
            },
            {
              RANK: '10',
              VOTE_IDX: '208',
              STAR_IDX: '606',
              STAR_GROUP_IDX: '412',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/412/606/HASH_0e4023f52da216dd65bc3fb74600ba12284bd63b0899fc198899c4756f303d18.jpg',
              VOTE_CNT: '4489846',
              TOP_LAYER_IDX: '552',
              STAR_NAME: '한승우',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/412/606/HASH_0e4023f52da216dd65bc3fb74600ba12284bd63b0899fc198899c4756f303d18.jpg',
              STAR_GROUP_NAME: '빅톤',
            },
            {
              RANK: '11',
              VOTE_IDX: '208',
              STAR_IDX: '5',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/51.png',
              VOTE_CNT: '4095957',
              TOP_LAYER_IDX: '5',
              STAR_NAME: '카이',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/51.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '12',
              VOTE_IDX: '208',
              STAR_IDX: '12',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1252.png',
              VOTE_CNT: '3971307',
              TOP_LAYER_IDX: '12',
              STAR_NAME: '슈가',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1252.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '13',
              VOTE_IDX: '208',
              STAR_IDX: '1011',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/10110.png',
              VOTE_CNT: '3394702',
              TOP_LAYER_IDX: '725',
              STAR_NAME: '김우석',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/10110.png',
              STAR_GROUP_NAME: '김우석(Kim Woo Seok)',
            },
            {
              RANK: '14',
              VOTE_IDX: '208',
              STAR_IDX: '2',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/21.png',
              VOTE_CNT: '2644512',
              TOP_LAYER_IDX: '2',
              STAR_NAME: '찬열',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/21.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '15',
              VOTE_IDX: '208',
              STAR_IDX: '1010',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/955497.jpg',
              VOTE_CNT: '2014913',
              TOP_LAYER_IDX: '784',
              STAR_NAME: 'WOODZ',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/955497.jpg',
              STAR_GROUP_NAME: 'WOODZ',
            },
            {
              RANK: '16',
              VOTE_IDX: '208',
              STAR_IDX: '4',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/41.png',
              VOTE_CNT: '1948964',
              TOP_LAYER_IDX: '4',
              STAR_NAME: '시우민',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/41.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '17',
              VOTE_IDX: '208',
              STAR_IDX: '6',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/61.png',
              VOTE_CNT: '1661668',
              TOP_LAYER_IDX: '6',
              STAR_NAME: '백현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/61.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '18',
              VOTE_IDX: '208',
              STAR_IDX: '1153',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1153546.png',
              VOTE_CNT: '1369263',
              TOP_LAYER_IDX: '965',
              STAR_NAME: '희승',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1153546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '19',
              VOTE_IDX: '208',
              STAR_IDX: '774',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7740.png',
              VOTE_CNT: '1095849',
              TOP_LAYER_IDX: '116',
              STAR_NAME: '김재환',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7740.png',
              STAR_GROUP_NAME: '김재환(Kim Jaehwan)',
            },
            {
              RANK: '20',
              VOTE_IDX: '208',
              STAR_IDX: '775',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7750.png',
              VOTE_CNT: '1045828',
              TOP_LAYER_IDX: '129',
              STAR_NAME: '박지훈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7750.png',
              STAR_GROUP_NAME: '박지훈(Park Jihoon)',
            },
            {
              RANK: '21',
              VOTE_IDX: '208',
              STAR_IDX: '14',
              STAR_GROUP_IDX: '52',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1452.png',
              VOTE_CNT: '1026239',
              TOP_LAYER_IDX: '14',
              STAR_NAME: 'RM',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1452.png',
              STAR_GROUP_NAME: 'BTS (Bangtan Boys)',
            },
            {
              RANK: '22',
              VOTE_IDX: '208',
              STAR_IDX: '7',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/71.png',
              VOTE_CNT: '969404',
              TOP_LAYER_IDX: '7',
              STAR_NAME: '수호',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/71.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '23',
              VOTE_IDX: '208',
              STAR_IDX: '819',
              STAR_GROUP_IDX: '491',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/819491.jpg',
              VOTE_CNT: '941257',
              TOP_LAYER_IDX: '154',
              STAR_NAME: '이대휘',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/819491.jpg',
              STAR_GROUP_NAME: 'AB6IX',
            },
            {
              RANK: '24',
              VOTE_IDX: '208',
              STAR_IDX: '8',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/1/8/HASH_94be8f54802c5f41750f5c2aa59e25e1749fd29a8f4f0998a0362d839f18eca5.jpg',
              VOTE_CNT: '891996',
              TOP_LAYER_IDX: '8',
              STAR_NAME: '세훈',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/1/8/HASH_94be8f54802c5f41750f5c2aa59e25e1749fd29a8f4f0998a0362d839f18eca5.jpg',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '25',
              VOTE_IDX: '208',
              STAR_IDX: '978',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/9780.png',
              VOTE_CNT: '784361',
              TOP_LAYER_IDX: '772',
              STAR_NAME: '이진혁',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/9780.png',
              STAR_GROUP_NAME: 'Lee Jin hyuk',
            },
            {
              RANK: '26',
              VOTE_IDX: '208',
              STAR_IDX: '1149',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1149546.png',
              VOTE_CNT: '713996',
              TOP_LAYER_IDX: '961',
              STAR_NAME: '성훈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1149546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '27',
              VOTE_IDX: '208',
              STAR_IDX: '1148',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1148546.png',
              VOTE_CNT: '659657',
              TOP_LAYER_IDX: '960',
              STAR_NAME: '선우',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1148546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '28',
              VOTE_IDX: '208',
              STAR_IDX: '1151',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1151546.png',
              VOTE_CNT: '614175',
              TOP_LAYER_IDX: '963',
              STAR_NAME: '제이',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1151546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '29',
              VOTE_IDX: '208',
              STAR_IDX: '1150',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1150546.png',
              VOTE_CNT: '605127',
              TOP_LAYER_IDX: '962',
              STAR_NAME: '정원',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1150546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '30',
              VOTE_IDX: '208',
              STAR_IDX: '200',
              STAR_GROUP_IDX: '21',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/20021.png',
              VOTE_CNT: '561618',
              TOP_LAYER_IDX: '200',
              STAR_NAME: '태민',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/20021.png',
              STAR_GROUP_NAME: 'SHINee',
            },
            {
              RANK: '31',
              VOTE_IDX: '208',
              STAR_IDX: '316',
              STAR_GROUP_IDX: '19',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/31619.png',
              VOTE_CNT: '507456',
              TOP_LAYER_IDX: '301',
              STAR_NAME: '시원',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/31619.png',
              STAR_GROUP_NAME: 'Super Junior',
            },
            {
              RANK: '32',
              VOTE_IDX: '208',
              STAR_IDX: '469',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/469444.png',
              VOTE_CNT: '484544',
              TOP_LAYER_IDX: '446',
              STAR_NAME: '리노',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/469444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '33',
              VOTE_IDX: '208',
              STAR_IDX: '1152',
              STAR_GROUP_IDX: '546',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1152546.png',
              VOTE_CNT: '483894',
              TOP_LAYER_IDX: '964',
              STAR_NAME: '제이크',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1152546.png',
              STAR_GROUP_NAME: '엔하이픈(ENHYPEN)',
            },
            {
              RANK: '34',
              VOTE_IDX: '208',
              STAR_IDX: '818',
              STAR_GROUP_IDX: '491',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/818491.png',
              VOTE_CNT: '468150',
              TOP_LAYER_IDX: '128',
              STAR_NAME: '박우진',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/818491.png',
              STAR_GROUP_NAME: 'AB6IX',
            },
            {
              RANK: '35',
              VOTE_IDX: '208',
              STAR_IDX: '1606',
              STAR_GROUP_IDX: '627',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1606627.png',
              VOTE_CNT: '407979',
              TOP_LAYER_IDX: '1304',
              STAR_NAME: '한빈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1606627.png',
              STAR_GROUP_NAME: '템페스트(TEMPEST)',
            },
            {
              RANK: '36',
              VOTE_IDX: '208',
              STAR_IDX: '773',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7730.png',
              VOTE_CNT: '394050',
              TOP_LAYER_IDX: '138',
              STAR_NAME: '옹성우',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7730.png',
              STAR_GROUP_NAME: '옹성우(Ong Seongwu)',
            },
            {
              RANK: '37',
              VOTE_IDX: '208',
              STAR_IDX: '771',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/7710.png',
              VOTE_CNT: '358415',
              TOP_LAYER_IDX: '148',
              STAR_NAME: '윤지성',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/7710.png',
              STAR_GROUP_NAME: '윤지성(Yoon Jiseong)',
            },
            {
              RANK: '38',
              VOTE_IDX: '208',
              STAR_IDX: '28',
              STAR_GROUP_IDX: '2',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/282.png',
              VOTE_CNT: '306008',
              TOP_LAYER_IDX: '28',
              STAR_NAME: 'Jay B',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/282.png',
              STAR_GROUP_NAME: 'GOT7',
            },
            {
              RANK: '39',
              VOTE_IDX: '208',
              STAR_IDX: '1044',
              STAR_GROUP_IDX: '522',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1044522.png',
              VOTE_CNT: '285012',
              TOP_LAYER_IDX: '744',
              STAR_NAME: '형준',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1044522.png',
              STAR_GROUP_NAME: '크래비티(CRAVITY)',
            },
            {
              RANK: '40',
              VOTE_IDX: '208',
              STAR_IDX: '1672',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/16720.png',
              VOTE_CNT: '277708',
              TOP_LAYER_IDX: '117',
              STAR_NAME: '김종현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/16720.png',
              STAR_GROUP_NAME: '김종현',
            },
            {
              RANK: '41',
              VOTE_IDX: '208',
              STAR_IDX: '241',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/241360.jpg',
              VOTE_CNT: '271170',
              TOP_LAYER_IDX: '241',
              STAR_NAME: '런쥔',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/241360.jpg',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '42',
              VOTE_IDX: '208',
              STAR_IDX: '414',
              STAR_GROUP_IDX: '394',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/394/414/HASH_03b28504bf12e8528b7a33589c9809d1d6320f0a84967734bd695c087443340d.jpg',
              VOTE_CNT: '266816',
              TOP_LAYER_IDX: '391',
              STAR_NAME: '은지원',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/394/414/HASH_03b28504bf12e8528b7a33589c9809d1d6320f0a84967734bd695c087443340d.jpg',
              STAR_GROUP_NAME: '젝스키스',
            },
            {
              RANK: '43',
              VOTE_IDX: '208',
              STAR_IDX: '471',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/471444.png',
              VOTE_CNT: '264527',
              TOP_LAYER_IDX: '448',
              STAR_NAME: '현진',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/471444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '44',
              VOTE_IDX: '208',
              STAR_IDX: '3',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/1/3/HASH_a56563a0ea1146f0f1447ff2a17d33d4.jpg',
              VOTE_CNT: '243774',
              TOP_LAYER_IDX: '3',
              STAR_NAME: '레이',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/1/3/HASH_a56563a0ea1146f0f1447ff2a17d33d4.jpg',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '45',
              VOTE_IDX: '208',
              STAR_IDX: '812',
              STAR_GROUP_IDX: '490',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/812490.png',
              VOTE_CNT: '220525',
              TOP_LAYER_IDX: '700',
              STAR_NAME: '범규',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/812490.png',
              STAR_GROUP_NAME: 'TXT',
            },
            {
              RANK: '46',
              VOTE_IDX: '208',
              STAR_IDX: '1144',
              STAR_GROUP_IDX: '544',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1144544.png',
              VOTE_CNT: '215352',
              TOP_LAYER_IDX: '957',
              STAR_NAME: '소정환',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1144544.png',
              STAR_GROUP_NAME: 'TREASURE',
            },
            {
              RANK: '47',
              VOTE_IDX: '208',
              STAR_IDX: '1',
              STAR_GROUP_IDX: '1',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/11.png',
              VOTE_CNT: '215174',
              TOP_LAYER_IDX: '1',
              STAR_NAME: '첸',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/11.png',
              STAR_GROUP_NAME: 'EXO',
            },
            {
              RANK: '48',
              VOTE_IDX: '208',
              STAR_IDX: '1673',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/16730.png',
              VOTE_CNT: '212972',
              TOP_LAYER_IDX: '99',
              STAR_NAME: '백호',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/16730.png',
              STAR_GROUP_NAME: '백호',
            },
            {
              RANK: '49',
              VOTE_IDX: '208',
              STAR_IDX: '196',
              STAR_GROUP_IDX: '21',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/21/196/HASH_018179b50ee8d655d6336451490e07adccdf270557dcebbb9a3e661caf514bbd.jpg',
              VOTE_CNT: '211959',
              TOP_LAYER_IDX: '196',
              STAR_NAME: '온유',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/21/196/HASH_018179b50ee8d655d6336451490e07adccdf270557dcebbb9a3e661caf514bbd.jpg',
              STAR_GROUP_NAME: 'SHINee',
            },
            {
              RANK: '50',
              VOTE_IDX: '208',
              STAR_IDX: '199',
              STAR_GROUP_IDX: '21',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/21/199/HASH_ce69be0f93efe7f295ebcb027168f0234b5195865800fdc5c5fdd51c851e036d.jpg',
              VOTE_CNT: '207442',
              TOP_LAYER_IDX: '199',
              STAR_NAME: '민호',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/21/199/HASH_ce69be0f93efe7f295ebcb027168f0234b5195865800fdc5c5fdd51c851e036d.jpg',
              STAR_GROUP_NAME: 'SHINee',
            },
            {
              RANK: '51',
              VOTE_IDX: '208',
              STAR_IDX: '36',
              STAR_GROUP_IDX: '254',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/36254.png',
              VOTE_CNT: '196137',
              TOP_LAYER_IDX: '36',
              STAR_NAME: '정한',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/36254.png',
              STAR_GROUP_NAME: '세븐틴(Seventeen)',
            },
            {
              RANK: '52',
              VOTE_IDX: '208',
              STAR_IDX: '1892',
              STAR_GROUP_IDX: '674',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1892674.png',
              VOTE_CNT: '191151',
              TOP_LAYER_IDX: '1446',
              STAR_NAME: '성한빈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1892674.png',
              STAR_GROUP_NAME: '제로베이스원(ZEROBASEONE)',
            },
            {
              RANK: '53',
              VOTE_IDX: '208',
              STAR_IDX: '1143',
              STAR_GROUP_IDX: '544',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1143544.png',
              VOTE_CNT: '189151',
              TOP_LAYER_IDX: '956',
              STAR_NAME: '박정우',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1143544.png',
              STAR_GROUP_NAME: 'TREASURE',
            },
            {
              RANK: '54',
              VOTE_IDX: '208',
              STAR_IDX: '1190',
              STAR_GROUP_IDX: '551',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1190551.png',
              VOTE_CNT: '169937',
              TOP_LAYER_IDX: '724',
              STAR_NAME: '김요한',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1190551.png',
              STAR_GROUP_NAME: '위아이(WEi)',
            },
            {
              RANK: '55',
              VOTE_IDX: '208',
              STAR_IDX: '1671',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/16710.png',
              VOTE_CNT: '153004',
              TOP_LAYER_IDX: '195',
              STAR_NAME: '황민현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/16710.png',
              STAR_GROUP_NAME: '황민현',
            },
            {
              RANK: '56',
              VOTE_IDX: '208',
              STAR_IDX: '472',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/472444.png',
              VOTE_CNT: '143951',
              TOP_LAYER_IDX: '449',
              STAR_NAME: '한',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/472444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '57',
              VOTE_IDX: '208',
              STAR_IDX: '234',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/360/234/HASH_45e619dacf529139fb5d5225d9d460bb3284cfe11f0ef5ca461dda971aeed052.jpg',
              VOTE_CNT: '139805',
              TOP_LAYER_IDX: '234',
              STAR_NAME: '유타',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/360/234/HASH_45e619dacf529139fb5d5225d9d460bb3284cfe11f0ef5ca461dda971aeed052.jpg',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '58',
              VOTE_IDX: '208',
              STAR_IDX: '470',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/470444.png',
              VOTE_CNT: '133655',
              TOP_LAYER_IDX: '447',
              STAR_NAME: '창빈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/470444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '59',
              VOTE_IDX: '208',
              STAR_IDX: '467',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/467444.png',
              VOTE_CNT: '125993',
              TOP_LAYER_IDX: '444',
              STAR_NAME: '방찬',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/467444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '60',
              VOTE_IDX: '208',
              STAR_IDX: '439',
              STAR_GROUP_IDX: '405',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/405/439/HASH_cc9317ab93159451f848432d103fdd9a7a9f2ab7469d2cad27d4af71c7bb0ae3.jpg',
              VOTE_CNT: '125305',
              TOP_LAYER_IDX: '416',
              STAR_NAME: '로운',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/405/439/HASH_cc9317ab93159451f848432d103fdd9a7a9f2ab7469d2cad27d4af71c7bb0ae3.jpg',
              STAR_GROUP_NAME: 'SF9',
            },
            {
              RANK: '61',
              VOTE_IDX: '208',
              STAR_IDX: '371',
              STAR_GROUP_IDX: '389',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/389/371/HASH_84e2612d5c50ac10eddcf1998fe739ff9f6e14d7ba44d01aca3c215f1bdb8f96.jpg',
              VOTE_CNT: '120439',
              TOP_LAYER_IDX: '356',
              STAR_NAME: '후이',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/389/371/HASH_84e2612d5c50ac10eddcf1998fe739ff9f6e14d7ba44d01aca3c215f1bdb8f96.jpg',
              STAR_GROUP_NAME: 'PENTAGON',
            },
            {
              RANK: '62',
              VOTE_IDX: '208',
              STAR_IDX: '237',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/237360.png',
              VOTE_CNT: '112762',
              TOP_LAYER_IDX: '237',
              STAR_NAME: '재현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/237360.png',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '63',
              VOTE_IDX: '208',
              STAR_IDX: '207',
              STAR_GROUP_IDX: '316',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/207316.jpg',
              VOTE_CNT: '98360',
              TOP_LAYER_IDX: '207',
              STAR_NAME: '차은우',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/207316.jpg',
              STAR_GROUP_NAME: '아스트로(ASTRO)',
            },
            {
              RANK: '64',
              VOTE_IDX: '208',
              STAR_IDX: '1221',
              STAR_GROUP_IDX: '555',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1221555.png',
              VOTE_CNT: '83230',
              TOP_LAYER_IDX: '730',
              STAR_NAME: '도현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1221555.png',
              STAR_GROUP_NAME: 'BAE173',
            },
            {
              RANK: '65',
              VOTE_IDX: '208',
              STAR_IDX: '605',
              STAR_GROUP_IDX: '412',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/605412.jpg',
              VOTE_CNT: '79146',
              TOP_LAYER_IDX: '551',
              STAR_NAME: '강승식',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/605412.jpg',
              STAR_GROUP_NAME: '빅톤',
            },
            {
              RANK: '66',
              VOTE_IDX: '208',
              STAR_IDX: '1893',
              STAR_GROUP_IDX: '674',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1893674.png',
              VOTE_CNT: '74653',
              TOP_LAYER_IDX: '1480',
              STAR_NAME: '석매튜',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1893674.png',
              STAR_GROUP_NAME: '제로베이스원(ZEROBASEONE)',
            },
            {
              RANK: '67',
              VOTE_IDX: '208',
              STAR_IDX: '950',
              STAR_GROUP_IDX: '496',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/950496.jpg',
              VOTE_CNT: '73811',
              TOP_LAYER_IDX: '131',
              STAR_NAME: '배진영',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/950496.jpg',
              STAR_GROUP_NAME: 'CIX',
            },
            {
              RANK: '68',
              VOTE_IDX: '208',
              STAR_IDX: '197',
              STAR_GROUP_IDX: '21',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/21/197/HASH_fe812908ed2ca954a93be7bb1dd0473c2dec91edc24735ba542bde69bca34b25.jpg',
              VOTE_CNT: '73647',
              TOP_LAYER_IDX: '197',
              STAR_NAME: '종현',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/21/197/HASH_fe812908ed2ca954a93be7bb1dd0473c2dec91edc24735ba542bde69bca34b25.jpg',
              STAR_GROUP_NAME: 'SHINee',
            },
            {
              RANK: '69',
              VOTE_IDX: '208',
              STAR_IDX: '1891',
              STAR_GROUP_IDX: '674',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1891674.png',
              VOTE_CNT: '69286',
              TOP_LAYER_IDX: '1498',
              STAR_NAME: '장하오 ',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1891674.png',
              STAR_GROUP_NAME: '제로베이스원(ZEROBASEONE)',
            },
            {
              RANK: '70',
              VOTE_IDX: '208',
              STAR_IDX: '1133',
              STAR_GROUP_IDX: '544',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1133544.png',
              VOTE_CNT: '65886',
              TOP_LAYER_IDX: '946',
              STAR_NAME: '최현석',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1133544.png',
              STAR_GROUP_NAME: 'TREASURE',
            },
            {
              RANK: '71',
              VOTE_IDX: '208',
              STAR_IDX: '240',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/360/240/HASH_686384b0ed212ab7c5fd624128626345c9d98a338bc9c32aaf73772f951ba428.jpg',
              VOTE_CNT: '64179',
              TOP_LAYER_IDX: '240',
              STAR_NAME: '해찬',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/360/240/HASH_686384b0ed212ab7c5fd624128626345c9d98a338bc9c32aaf73772f951ba428.jpg',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '72',
              VOTE_IDX: '208',
              STAR_IDX: '208',
              STAR_GROUP_IDX: '316',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/316/208/HASH_e4241f473dfa80cca28b3fe2030203f223f46817beb85ef3156676f1c72a2577.jpg',
              VOTE_CNT: '63292',
              TOP_LAYER_IDX: '208',
              STAR_NAME: '문빈',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/316/208/HASH_e4241f473dfa80cca28b3fe2030203f223f46817beb85ef3156676f1c72a2577.jpg',
              STAR_GROUP_NAME: '아스트로(ASTRO)',
            },
            {
              RANK: '73',
              VOTE_IDX: '208',
              STAR_IDX: '474',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/474444.png',
              VOTE_CNT: '61053',
              TOP_LAYER_IDX: '451',
              STAR_NAME: '승민',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/474444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '74',
              VOTE_IDX: '208',
              STAR_IDX: '40',
              STAR_GROUP_IDX: '254',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/40254.png',
              VOTE_CNT: '60285',
              TOP_LAYER_IDX: '40',
              STAR_NAME: '원우',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/40254.png',
              STAR_GROUP_NAME: '세븐틴(Seventeen)',
            },
            {
              RANK: '75',
              VOTE_IDX: '208',
              STAR_IDX: '1898',
              STAR_GROUP_IDX: '674',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1898674.png',
              VOTE_CNT: '60177',
              TOP_LAYER_IDX: '1435',
              STAR_NAME: '김지웅',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1898674.png',
              STAR_GROUP_NAME: '제로베이스원(ZEROBASEONE)',
            },
            {
              RANK: '76',
              VOTE_IDX: '208',
              STAR_IDX: '315',
              STAR_GROUP_IDX: '19',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/31519.jpg',
              VOTE_CNT: '57203',
              TOP_LAYER_IDX: '300',
              STAR_NAME: '은혁',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/31519.jpg',
              STAR_GROUP_NAME: 'Super Junior',
            },
            {
              RANK: '77',
              VOTE_IDX: '208',
              STAR_IDX: '69',
              STAR_GROUP_IDX: '184',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/184/69/HASH_19231b084f0c0da78ac461d5154c949d131849a501db2ba5576e8c7b36652644.jpg',
              VOTE_CNT: '56790',
              TOP_LAYER_IDX: '69',
              STAR_NAME: '주헌',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/184/69/HASH_19231b084f0c0da78ac461d5154c949d131849a501db2ba5576e8c7b36652644.jpg',
              STAR_GROUP_NAME: '몬스타엑스(MONSTA X)',
            },
            {
              RANK: '78',
              VOTE_IDX: '208',
              STAR_IDX: '473',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/473444.png',
              VOTE_CNT: '55266',
              TOP_LAYER_IDX: '450',
              STAR_NAME: '필릭스',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/473444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '79',
              VOTE_IDX: '208',
              STAR_IDX: '64',
              STAR_GROUP_IDX: '184',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/184/64/HASH_d7cd09ac832ce1b892e79fb2b9e50fc5ed31b210a8e95818aa70844a6223f096.jpg',
              VOTE_CNT: '45601',
              TOP_LAYER_IDX: '64',
              STAR_NAME: '셔누',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/184/64/HASH_d7cd09ac832ce1b892e79fb2b9e50fc5ed31b210a8e95818aa70844a6223f096.jpg',
              STAR_GROUP_NAME: '몬스타엑스(MONSTA X)',
            },
            {
              RANK: '80',
              VOTE_IDX: '208',
              STAR_IDX: '475',
              STAR_GROUP_IDX: '444',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/475444.png',
              VOTE_CNT: '43963',
              TOP_LAYER_IDX: '452',
              STAR_NAME: '아이엔',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/475444.png',
              STAR_GROUP_NAME: '스트레이 키즈',
            },
            {
              RANK: '81',
              VOTE_IDX: '208',
              STAR_IDX: '1279',
              STAR_GROUP_IDX: '0',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/12790.png',
              VOTE_CNT: '40583',
              TOP_LAYER_IDX: '65',
              STAR_NAME: '원호',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/12790.png',
              STAR_GROUP_NAME: 'Wonho',
            },
            {
              RANK: '82',
              VOTE_IDX: '208',
              STAR_IDX: '811',
              STAR_GROUP_IDX: '490',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/811490.png',
              VOTE_CNT: '39657',
              TOP_LAYER_IDX: '699',
              STAR_NAME: '수빈',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/811490.png',
              STAR_GROUP_NAME: 'TXT',
            },
            {
              RANK: '83',
              VOTE_IDX: '208',
              STAR_IDX: '813',
              STAR_GROUP_IDX: '490',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/813490.png',
              VOTE_CNT: '38923',
              TOP_LAYER_IDX: '701',
              STAR_NAME: '태현',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/813490.png',
              STAR_GROUP_NAME: 'TXT',
            },
            {
              RANK: '84',
              VOTE_IDX: '208',
              STAR_IDX: '198',
              STAR_GROUP_IDX: '21',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/21/198/HASH_23dc531be05f630a5416b1548e3b2057dd5ea91d208608b9d9f69f30a3393829.jpg',
              VOTE_CNT: '38739',
              TOP_LAYER_IDX: '198',
              STAR_NAME: '키',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/21/198/HASH_23dc531be05f630a5416b1548e3b2057dd5ea91d208608b9d9f69f30a3393829.jpg',
              STAR_GROUP_NAME: 'SHINee',
            },
            {
              RANK: '85',
              VOTE_IDX: '208',
              STAR_IDX: '242',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/360/242/HASH_fd70fd96a1eeb8d9d34a127432ff68d2835df4203542280a1521cc3cab351ae2.jpg',
              VOTE_CNT: '33650',
              TOP_LAYER_IDX: '242',
              STAR_NAME: '제노',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/360/242/HASH_fd70fd96a1eeb8d9d34a127432ff68d2835df4203542280a1521cc3cab351ae2.jpg',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '86',
              VOTE_IDX: '208',
              STAR_IDX: '1685',
              STAR_GROUP_IDX: '644',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1685644.png',
              VOTE_CNT: '28693',
              TOP_LAYER_IDX: '1361',
              STAR_NAME: '천준혁',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1685644.png',
              STAR_GROUP_NAME: 'THE NEW SIX',
            },
            {
              RANK: '87',
              VOTE_IDX: '208',
              STAR_IDX: '212',
              STAR_GROUP_IDX: '316',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/316/212/HASH_cb58e10ff702574766d86431e9bdb596fd4292330f1d9539946190709bfd5e2a.jpg',
              VOTE_CNT: '28192',
              TOP_LAYER_IDX: '212',
              STAR_NAME: '윤산하',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/316/212/HASH_cb58e10ff702574766d86431e9bdb596fd4292330f1d9539946190709bfd5e2a.jpg',
              STAR_GROUP_NAME: '아스트로(ASTRO)',
            },
            {
              RANK: '88',
              VOTE_IDX: '208',
              STAR_IDX: '29',
              STAR_GROUP_IDX: '2',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/292.png',
              VOTE_CNT: '26000',
              TOP_LAYER_IDX: '29',
              STAR_NAME: '마크',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/292.png',
              STAR_GROUP_NAME: 'GOT7',
            },
            {
              RANK: '89',
              VOTE_IDX: '208',
              STAR_IDX: '1142',
              STAR_GROUP_IDX: '544',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1142544.png',
              VOTE_CNT: '24920',
              TOP_LAYER_IDX: '955',
              STAR_NAME: '하루토',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1142544.png',
              STAR_GROUP_NAME: 'TREASURE',
            },
            {
              RANK: '90',
              VOTE_IDX: '208',
              STAR_IDX: '810',
              STAR_GROUP_IDX: '490',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/810490.png',
              VOTE_CNT: '18947',
              TOP_LAYER_IDX: '698',
              STAR_NAME: '연준',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/810490.png',
              STAR_GROUP_NAME: 'TXT',
            },
            {
              RANK: '91',
              VOTE_IDX: '208',
              STAR_IDX: '244',
              STAR_GROUP_IDX: '360',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/244360.png',
              VOTE_CNT: '16451',
              TOP_LAYER_IDX: '244',
              STAR_NAME: '천러',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/244360.png',
              STAR_GROUP_NAME: '엔시티 (NCT)',
            },
            {
              RANK: '92',
              VOTE_IDX: '208',
              STAR_IDX: '209',
              STAR_GROUP_IDX: '316',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/316/209/HASH_43741f47f31feea1df1d7b69fb46588ba1939bcfcff55d4257e07dd423e9adcd.jpg',
              VOTE_CNT: '14560',
              TOP_LAYER_IDX: '209',
              STAR_NAME: 'MJ',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/316/209/HASH_43741f47f31feea1df1d7b69fb46588ba1939bcfcff55d4257e07dd423e9adcd.jpg',
              STAR_GROUP_NAME: '아스트로(ASTRO)',
            },
            {
              RANK: '93',
              VOTE_IDX: '208',
              STAR_IDX: '788',
              STAR_GROUP_IDX: '488',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/788488.png',
              VOTE_CNT: '9938',
              TOP_LAYER_IDX: '683',
              STAR_NAME: '여상',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/788488.png',
              STAR_GROUP_NAME: 'ATEEZ',
            },
            {
              RANK: '94',
              VOTE_IDX: '208',
              STAR_IDX: '1899',
              STAR_GROUP_IDX: '674',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/1899674.png',
              VOTE_CNT: '8672',
              TOP_LAYER_IDX: '1468',
              STAR_NAME: '한유진',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/1899674.png',
              STAR_GROUP_NAME: '제로베이스원(ZEROBASEONE)',
            },
            {
              RANK: '95',
              VOTE_IDX: '208',
              STAR_IDX: '34',
              STAR_GROUP_IDX: '2',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/342.png',
              VOTE_CNT: '7880',
              TOP_LAYER_IDX: '34',
              STAR_NAME: '유겸',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/342.png',
              STAR_GROUP_NAME: 'GOT7',
            },
            {
              RANK: '96',
              VOTE_IDX: '208',
              STAR_IDX: '790',
              STAR_GROUP_IDX: '488',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/790488.png',
              VOTE_CNT: '6350',
              TOP_LAYER_IDX: '685',
              STAR_NAME: '민기',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/790488.png',
              STAR_GROUP_NAME: 'ATEEZ',
            },
            {
              RANK: '97',
              VOTE_IDX: '208',
              STAR_IDX: '31',
              STAR_GROUP_IDX: '2',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/312.png',
              VOTE_CNT: '4746',
              TOP_LAYER_IDX: '31',
              STAR_NAME: '진영',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/312.png',
              STAR_GROUP_NAME: 'GOT7',
            },
            {
              RANK: '98',
              VOTE_IDX: '208',
              STAR_IDX: '70',
              STAR_GROUP_IDX: '184',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/184/70/HASH_d3b906b1baccd0f213c95a7be2b57d08367f9e6162ba65756737680ca57015c1.jpg',
              VOTE_CNT: '4112',
              TOP_LAYER_IDX: '70',
              STAR_NAME: 'I.M',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/184/70/HASH_d3b906b1baccd0f213c95a7be2b57d08367f9e6162ba65756737680ca57015c1.jpg',
              STAR_GROUP_NAME: '몬스타엑스(MONSTA X)',
            },
            {
              RANK: '99',
              VOTE_IDX: '208',
              STAR_IDX: '32',
              STAR_GROUP_IDX: '2',
              PROFILE_IMG: 'https://photo-cf.appphotocard.com/star_icon/322.png',
              VOTE_CNT: '4045',
              TOP_LAYER_IDX: '32',
              STAR_NAME: '영재',
              STAR_DEFAULT_PHOTO: 'https://photo-cf.appphotocard.com/star_icon/322.png',
              STAR_GROUP_NAME: 'GOT7',
            },
            {
              RANK: '100',
              VOTE_IDX: '208',
              STAR_IDX: '68',
              STAR_GROUP_IDX: '184',
              PROFILE_IMG:
                'https://photo-cf.appphotocard.com/184/68/HASH_217d4c117f747b086feec77033dd209110c82fffc71415829791c39179775364.jpg',
              VOTE_CNT: '3790',
              TOP_LAYER_IDX: '68',
              STAR_NAME: '형원',
              STAR_DEFAULT_PHOTO:
                'https://photo-cf.appphotocard.com/184/68/HASH_217d4c117f747b086feec77033dd209110c82fffc71415829791c39179775364.jpg',
              STAR_GROUP_NAME: '몬스타엑스(MONSTA X)',
            },
          ],
        },
      },
      TIMESTAMP: 1689845801,
    },
  };
  return response;
};
